"use client";
import Link from "next/link";
import {FormEvent,useEffect,useMemo,useState} from "react";
import {ArrowLeft,Check,ChevronRight,Image as ImageIcon,LayoutTemplate,Monitor,Palette,PanelBottom,PanelTop,RefreshCw,Save,Settings2,Smartphone,Sparkles} from "lucide-react";
import {supabase} from "@/lib/supabase";
import "./ui-settings.css";

type Tab="branding"|"colors"|"header"|"footer"|"mobile"|"modules"|"layout"|"advanced";
const tabs:[Tab,string,any,string][]=[
 ["branding","Branding",ImageIcon,"Logos, splash and favicon"],["colors","Colors & Type",Palette,"Theme palette and typography"],["header","Header",PanelTop,"Desktop header and navigation"],["footer","Footer",PanelBottom,"Footer visibility and structure"],["mobile","Mobile",Smartphone,"Phone header, nav and density"],["modules","Modules",LayoutTemplate,"Show or hide frontend sections"],["layout","Layout",Monitor,"Widths, spacing and effects"],["advanced","Advanced",Settings2,"Custom CSS and advanced options"]
];
const boolFields:{key:string;label:string;help?:string}[]=[
 {key:"show_home_hero",label:"Homepage hero"},{key:"show_home_services",label:"Services section"},{key:"show_home_memories",label:"Spiritual Memories"},{key:"show_home_contests",label:"Contests section"},{key:"show_home_businesses",label:"Featured businesses"},{key:"show_home_videos",label:"Public videos"},{key:"show_home_winners",label:"Winner section"},{key:"show_context_help",label:"Floating Help button"},{key:"show_social_share",label:"Social sharing blocks"}
];
const defaults:any={primary_color:"#7d0739",secondary_color:"#5f062d",accent_color:"#f6b51b",background_color:"#fffaf1",surface_color:"#fffdf9",text_color:"#321820",muted_color:"#78666b",success_color:"#2f8a49",danger_color:"#b42318",font_family:"Inter",heading_font_family:"Georgia",base_font_size:16,border_radius:18,mobile_content_padding:14,desktop_content_width:1440,desktop_content_padding:42,header_style:"standard",footer_style:"standard",mobile_header_style:"compact",mobile_card_density:"comfortable",animation_level:"normal"};

export default function WebsiteUISettings(){
 const [tab,setTab]=useState<Tab>("branding"),[row,setRow]=useState<any>(null),[form,setForm]=useState<any>(defaults),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[msg,setMsg]=useState("");
 useEffect(()=>{(async()=>{const {data:u}=await supabase.auth.getUser();if(!u.user){setLoading(false);return}const {data:r}=await supabase.from("user_roles").select("role").eq("user_id",u.user.id).eq("role","admin").maybeSingle();if(!r){setLoading(false);return}const {data}=await supabase.from("site_ui_settings").select("*").limit(1).maybeSingle();if(data){setRow(data);setForm({...defaults,...data,desktop_nav_text:JSON.stringify(data.desktop_nav_items||[],null,2),mobile_nav_text:JSON.stringify(data.mobile_bottom_nav_items||[],null,2),footer_columns_text:JSON.stringify(data.footer_columns||[],null,2),metadata_text:JSON.stringify(data.metadata||{},null,2)})}setLoading(false)})()},[]);
 const set=(k:string,v:any)=>setForm((p:any)=>({...p,[k]:v}));
 async function save(e?:FormEvent){e?.preventDefault();setSaving(true);setMsg("");let desktop:any=[],mobile:any=[],footer:any=[],metadata:any={};try{desktop=JSON.parse(form.desktop_nav_text||"[]");mobile=JSON.parse(form.mobile_nav_text||"[]");footer=JSON.parse(form.footer_columns_text||"[]");metadata=JSON.parse(form.metadata_text||"{}")}catch{setSaving(false);setMsg("One of the JSON fields is invalid.");return}const payload={...form,desktop_nav_items:desktop,mobile_bottom_nav_items:mobile,footer_columns:footer,metadata,updated_at:new Date().toISOString()};delete payload.desktop_nav_text;delete payload.mobile_nav_text;delete payload.footer_columns_text;delete payload.metadata_text;const {error}=row?await supabase.from("site_ui_settings").update(payload).eq("id",row.id):await supabase.from("site_ui_settings").insert(payload);setSaving(false);setMsg(error?.message||"Website UI settings saved. Reload the public site to see the changes.")}
 const swatches=useMemo(()=>[["primary_color","Primary"],["secondary_color","Secondary"],["accent_color","Accent"],["background_color","Background"],["surface_color","Surface"],["text_color","Text"],["muted_color","Muted"],["success_color","Success"],["danger_color","Danger"]] as const,[]);
 if(loading)return <div className="ui-admin-loading"><Palette/><strong>Loading Website UI Settings…</strong></div>;
 return <div className="ui-admin"><aside className="ui-admin-side"><Link href="/admin" className="ui-back"><ArrowLeft size={16}/>Admin dashboard</Link><div className="ui-title"><span><Palette/></span><div><strong>Website UI</strong><small>Theme & frontend controls</small></div></div><nav>{tabs.map(([k,l,I,d])=><button key={k} className={tab===k?"active":""} onClick={()=>setTab(k)}><I size={18}/><span><b>{l}</b><small>{d}</small></span><ChevronRight size={15}/></button>)}</nav></aside><main className="ui-admin-main"><header><div><p>Appearance / Website UI</p><h1>{tabs.find(t=>t[0]===tab)?.[1]}</h1></div><div className="ui-head-actions"><Link href="/" target="_blank">Preview site</Link><button onClick={()=>location.reload()}><RefreshCw size={15}/></button><button className="save" onClick={()=>save()} disabled={saving}><Save size={15}/>{saving?"Saving…":"Save changes"}</button></div></header><form onSubmit={save} className="ui-settings-body">
 {tab==="branding"&&<Section title="Brand identity" intro="Set independent assets for desktop, mobile, header, footer and loading screens."><div className="ui-grid two"><Text f={form} set={set} k="site_name" l="Website name"/><Media f={form} set={set} k="desktop_logo_url" l="Desktop logo"/><Media f={form} set={set} k="mobile_logo_url" l="Mobile logo"/><Media f={form} set={set} k="header_logo_url" l="Header logo"/><Media f={form} set={set} k="footer_logo_url" l="Footer logo"/><Media f={form} set={set} k="splash_logo_url" l="Loading / splash icon"/><Media f={form} set={set} k="favicon_url" l="Favicon / browser icon"/></div><Link className="ui-media-link" href="/admin/media"><ImageIcon size={15}/>Open Media Library</Link></Section>}
 {tab==="colors"&&<><Section title="Global color palette" intro="These colors feed the main CSS variables used across the public website."><div className="ui-swatches">{swatches.map(([k,l])=><label key={k}><span>{l}</span><div><input type="color" value={form[k]||"#000000"} onChange={e=>set(k,e.target.value)}/><input value={form[k]||""} onChange={e=>set(k,e.target.value)}/></div></label>)}</div></Section><Section title="Typography"><div className="ui-grid two"><Text f={form} set={set} k="font_family" l="Body font family"/><Text f={form} set={set} k="heading_font_family" l="Heading font family"/><NumberField f={form} set={set} k="base_font_size" l="Base font size (px)"/></div></Section></>}
 {tab==="header"&&<><Section title="Desktop header"><div className="ui-grid two"><Select f={form} set={set} k="header_style" l="Header style" options={["standard","minimal","centered","transparent"]}/><Toggle f={form} set={set} k="header_sticky" l="Sticky header"/><Toggle f={form} set={set} k="show_header_logo" l="Show header logo"/><Toggle f={form} set={set} k="show_header_site_name" l="Show site name"/><Toggle f={form} set={set} k="show_header_tagline" l="Show tagline"/><Toggle f={form} set={set} k="show_header_videos" l="Show Videos icon"/><Toggle f={form} set={set} k="show_header_notifications" l="Show Notifications icon"/><Toggle f={form} set={set} k="show_header_account" l="Show Account icon"/></div></Section><Section title="Desktop navigation" intro="Edit menu labels and destinations. Keep valid JSON."><JsonArea value={form.desktop_nav_text||"[]"} onChange={v=>set("desktop_nav_text",v)}/></Section></>}
 {tab==="footer"&&<><Section title="Footer presentation"><div className="ui-grid two"><Select f={form} set={set} k="footer_style" l="Footer style" options={["standard","compact","minimal","large"]}/><Toggle f={form} set={set} k="show_footer_logo" l="Show footer logo"/><Toggle f={form} set={set} k="show_footer_description" l="Show description"/><Toggle f={form} set={set} k="show_footer_social" l="Show social links"/><Toggle f={form} set={set} k="show_footer_legal" l="Show legal links"/></div></Section><Section title="Custom footer columns" intro="Optional JSON-driven footer groups."><JsonArea value={form.footer_columns_text||"[]"} onChange={v=>set("footer_columns_text",v)}/></Section></>}
 {tab==="mobile"&&<><Section title="Mobile appearance"><div className="ui-grid two"><Select f={form} set={set} k="mobile_header_style" l="Mobile header" options={["compact","standard","minimal"]}/><Select f={form} set={set} k="mobile_card_density" l="Card density" options={["compact","comfortable","spacious"]}/><Toggle f={form} set={set} k="mobile_show_site_name" l="Show site name"/><Toggle f={form} set={set} k="mobile_show_tagline" l="Show tagline"/><Toggle f={form} set={set} k="mobile_bottom_nav" l="Show bottom navigation"/><NumberField f={form} set={set} k="mobile_content_padding" l="Mobile page padding (px)"/></div></Section><Section title="Mobile bottom menu"><JsonArea value={form.mobile_nav_text||"[]"} onChange={v=>set("mobile_nav_text",v)}/></Section></>}
 {tab==="modules"&&<Section title="Frontend module visibility" intro="Turn public features on or off without deleting their content."><div className="ui-module-grid">{boolFields.map(x=><Toggle key={x.key} f={form} set={set} k={x.key} l={x.label}/>)}</div></Section>}
 {tab==="layout"&&<><Section title="Desktop canvas"><div className="ui-grid two"><NumberField f={form} set={set} k="desktop_content_width" l="Maximum content width (px)"/><NumberField f={form} set={set} k="desktop_content_padding" l="Desktop side padding (px)"/><NumberField f={form} set={set} k="border_radius" l="Global border radius (px)"/><Text f={form} set={set} k="card_shadow" l="Card shadow CSS"/><Select f={form} set={set} k="animation_level" l="Animation level" options={["none","reduced","normal"]}/></div></Section><div className="ui-preview-card" style={{background:form.surface_color,borderRadius:Number(form.border_radius||18),boxShadow:form.card_shadow}}><Sparkles/><div><strong>Live style preview</strong><span>Surface, radius and shadow preview.</span></div><button style={{background:form.primary_color,color:"white"}}>Primary action</button></div></>}
 {tab==="advanced"&&<><Section title="Custom CSS" intro="Advanced override layer applied after the standard theme styles."><textarea className="ui-code" rows={14} value={form.custom_css||""} onChange={e=>set("custom_css",e.target.value)} placeholder="/* Add custom CSS here */"/></Section><Section title="Advanced metadata"><JsonArea value={form.metadata_text||"{}"} onChange={v=>set("metadata_text",v)}/></Section></>}
 <div className="ui-savebar"><div>{msg&&<span className={msg.includes("saved")?"success":"error"}><Check size={15}/>{msg}</span>}</div><button className="save" disabled={saving}><Save size={15}/>{saving?"Saving…":"Save Website UI"}</button></div></form></main></div>
}
function Section({title,intro,children}:{title:string;intro?:string;children:React.ReactNode}){return <section className="ui-setting-card"><div className="ui-section-title"><h2>{title}</h2>{intro&&<p>{intro}</p>}</div>{children}</section>}
function Text({f,set,k,l}:{f:any;set:any;k:string;l:string}){return <label className="ui-field"><span>{l}</span><input value={f[k]||""} onChange={e=>set(k,e.target.value)}/></label>}
function NumberField({f,set,k,l}:{f:any;set:any;k:string;l:string}){return <label className="ui-field"><span>{l}</span><input type="number" value={f[k]??""} onChange={e=>set(k,Number(e.target.value))}/></label>}
function Media({f,set,k,l}:{f:any;set:any;k:string;l:string}){return <label className="ui-field media"><span>{l}</span><div>{f[k]?<img src={f[k]} alt=""/>:<i><ImageIcon/></i>}<input placeholder="Media URL" value={f[k]||""} onChange={e=>set(k,e.target.value)}/></div></label>}
function Toggle({f,set,k,l}:{f:any;set:any;k:string;l:string}){return <label className="ui-toggle"><span><b>{l}</b><small>{f[k]===false?"Hidden / disabled":"Visible / enabled"}</small></span><input type="checkbox" checked={f[k]!==false} onChange={e=>set(k,e.target.checked)}/><i/></label>}
function Select({f,set,k,l,options}:{f:any;set:any;k:string;l:string;options:string[]}){return <label className="ui-field"><span>{l}</span><select value={f[k]||options[0]} onChange={e=>set(k,e.target.value)}>{options.map(x=><option key={x}>{x}</option>)}</select></label>}
function JsonArea({value,onChange}:{value:string;onChange:(v:string)=>void}){return <textarea className="ui-code" rows={10} value={value} onChange={e=>onChange(e.target.value)}/>}
