"use client";
import Link from "next/link";
import { useEffect,useMemo,useState } from "react";
import { ArrowLeft,BadgeCheck,Briefcase,Search,Shield,ShieldCheck,UserCog,UsersRound } from "lucide-react";
import { supabase } from "@/lib/supabase";
import { BrandIcon } from "@/components/BrandLogo";

const STAFF_ROLES=[
 {key:"admin",label:"Administrator",desc:"Full platform control"},
 {key:"moderator",label:"Moderator",desc:"Content review and moderation"},
 {key:"verification",label:"Verification Team",desc:"Verify businesses, submissions and account information"},
 {key:"support",label:"Support Team",desc:"Manage tickets and customer support"},
 {key:"finance",label:"Finance Team",desc:"Payments, refunds and payouts"},
 {key:"content_manager",label:"Content Manager",desc:"CMS, banners, pages and media"}
];
export default function AdminStaffPage(){
 const [user,setUser]=useState<any>(null),[allowed,setAllowed]=useState(false),[loading,setLoading]=useState(true),[profiles,setProfiles]=useState<any[]>([]),[roles,setRoles]=useState<any[]>([]),[staffMeta,setStaffMeta]=useState<any[]>([]),[q,setQ]=useState(""),[roleFilter,setRoleFilter]=useState("all"),[selected,setSelected]=useState<any>(null),[notice,setNotice]=useState("");
 async function load(){const [p,r,s]=await Promise.all([supabase.from("profiles").select("*").order("created_at",{ascending:false}),supabase.from("user_roles").select("*"),supabase.from("staff_profiles").select("*")]);setProfiles(p.data||[]);setRoles(r.data||[]);setStaffMeta(s.data||[])}
 useEffect(()=>{(async()=>{const {data:{user:u}}=await supabase.auth.getUser();setUser(u);if(!u){setLoading(false);return}const {data:r}=await supabase.from("user_roles").select("role").eq("user_id",u.id).eq("role","admin").maybeSingle();if(!r){setLoading(false);return}setAllowed(true);await load();setLoading(false)})()},[]);
 const roleMap=useMemo(()=>roles.reduce((a:any,r:any)=>{(a[r.user_id]??=[]).push(r.role);return a},{}),[roles]);
 const metaMap=useMemo(()=>Object.fromEntries(staffMeta.map(s=>[s.user_id,s])),[staffMeta]);
 const staff=profiles.filter(p=>(roleMap[p.id]||[]).some((r:string)=>STAFF_ROLES.some(s=>s.key===r)));
 const candidates=profiles.filter(p=>!(roleMap[p.id]||[]).some((r:string)=>STAFF_ROLES.some(s=>s.key===r)));
 const visible=staff.filter(p=>{const rs=roleMap[p.id]||[];const text=`${p.full_name||""} ${p.email||""} ${metaMap[p.id]?.department||""} ${metaMap[p.id]?.job_title||""}`.toLowerCase();return (!q||text.includes(q.toLowerCase()))&&(roleFilter==="all"||rs.includes(roleFilter))});
 async function addRole(id:string,role:string){await supabase.from("user_roles").upsert({user_id:id,role});const existing=metaMap[id];if(!existing)await supabase.from("staff_profiles").insert({user_id:id,department:role==="admin"?"Administration":"Operations",job_title:STAFF_ROLES.find(r=>r.key===role)?.label||role,is_active:true});await load();setNotice("Staff role added.")}
 async function removeRole(id:string,role:string){if(id===user?.id&&role==="admin"){setNotice("You cannot remove your own administrator role.");return}await supabase.from("user_roles").delete().eq("user_id",id).eq("role",role);const remaining=(roleMap[id]||[]).filter((r:string)=>r!==role&&STAFF_ROLES.some(s=>s.key===r));if(!remaining.length)await supabase.from("staff_profiles").delete().eq("user_id",id);await load();setNotice("Staff role removed.")}
 async function saveMeta(id:string,patch:any){await supabase.from("staff_profiles").upsert({user_id:id,...patch,updated_at:new Date().toISOString()});await load();setSelected((s:any)=>s?{...s,...patch}:s);setNotice("Staff profile updated.")}
 if(loading)return <div className="ma-loader"><BrandIcon size={110}/><strong>Loading Staff Management</strong></div>;
 if(!user||!allowed)return <div className="admin-auth-cover"><div className="admin-auth-card"><BrandIcon size={80}/><h1>Restricted</h1><p>Administrator access required.</p><Link className="admin-primary" href="/admin">Admin Login</Link></div></div>;
 return <div className="identity-admin"><header><div><Link href="/admin"><ArrowLeft size={15}/>Back to Admin</Link><h1>Staff & Roles</h1><p>Administrators, moderators, verification, support, finance and content operations.</p></div><Link className="identity-staff-link" href="/admin/users"><UsersRound size={15}/>Site Users</Link></header>
 <div className="identity-stats staff-stats"><article><ShieldCheck/><span>Total staff</span><strong>{staff.length}</strong></article><article><Shield/><span>Admins</span><strong>{staff.filter(p=>(roleMap[p.id]||[]).includes("admin")).length}</strong></article><article><UserCog/><span>Moderators</span><strong>{staff.filter(p=>(roleMap[p.id]||[]).includes("moderator")).length}</strong></article><article><BadgeCheck/><span>Verification</span><strong>{staff.filter(p=>(roleMap[p.id]||[]).includes("verification")).length}</strong></article></div>
 <main><section className="staff-role-cards">{STAFF_ROLES.map(r=><button key={r.key} className={roleFilter===r.key?"active":""} onClick={()=>setRoleFilter(roleFilter===r.key?"all":r.key)}><ShieldCheck/><strong>{r.label}</strong><span>{r.desc}</span><em>{staff.filter(p=>(roleMap[p.id]||[]).includes(r.key)).length}</em></button>)}</section>
 <div className="identity-toolbar"><div className="identity-search"><Search size={16}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search staff…"/></div><select className="staff-add-select" defaultValue="" onChange={async e=>{const [id,role]=e.target.value.split("|");if(id&&role)await addRole(id,role);e.target.value=""}}><option value="">+ Add existing user to staff</option>{candidates.flatMap(p=>STAFF_ROLES.map(r=><option key={`${p.id}-${r.key}`} value={`${p.id}|${r.key}`}>{p.full_name||p.email} → {r.label}</option>))}</select></div>
 <div className="identity-table"><div className="identity-row staff-head"><span>Staff member</span><span>Roles</span><span>Department / Title</span><span>Status</span><span>Manage</span></div>{visible.map(p=>{const rs=(roleMap[p.id]||[]).filter((r:string)=>STAFF_ROLES.some(s=>s.key===r));const meta=metaMap[p.id]||{};return <div className="identity-row staff-row" key={p.id}><div><strong>{p.full_name||"Staff Member"}</strong><small>{p.email||p.mobile}</small></div><div className="staff-role-pills">{rs.map((r:string)=><span key={r}>{STAFF_ROLES.find(x=>x.key===r)?.label||r}<button onClick={()=>removeRole(p.id,r)}>×</button></span>)}</div><div><strong>{meta.department||"Operations"}</strong><small>{meta.job_title||"Staff"}</small></div><div><em className={meta.is_active===false?"identity-badge inactive":"identity-badge active"}>{meta.is_active===false?"Inactive":"Active"}</em></div><div><button onClick={()=>setSelected({...p,...meta,roles:rs})}>Manage</button></div></div>})}{!visible.length&&<div className="identity-empty">No matching staff members.</div>}</div></main>
 {selected&&<div className="staff-modal-bg" onClick={()=>setSelected(null)}><section className="staff-modal" onClick={e=>e.stopPropagation()}><header><div><span>STAFF PROFILE</span><h2>{selected.full_name||selected.email}</h2><p>{selected.email}</p></div><button onClick={()=>setSelected(null)}>×</button></header><div className="staff-modal-body"><label>Department<input defaultValue={selected.department||""} onBlur={e=>saveMeta(selected.id,{department:e.target.value})}/></label><label>Job title<input defaultValue={selected.job_title||""} onBlur={e=>saveMeta(selected.id,{job_title:e.target.value})}/></label><label>Access status<select value={selected.is_active===false?"inactive":"active"} onChange={e=>saveMeta(selected.id,{is_active:e.target.value==="active"})}><option value="active">Active</option><option value="inactive">Inactive</option></select></label><label className="span-2">Internal notes<textarea rows={4} defaultValue={selected.notes||""} onBlur={e=>saveMeta(selected.id,{notes:e.target.value})}/></label><div className="span-2"><strong className="staff-label">Roles</strong><div className="staff-role-editor">{STAFF_ROLES.map(r=>{const on=(selected.roles||[]).includes(r.key);return <button className={on?"active":""} key={r.key} onClick={async()=>{if(on)await removeRole(selected.id,r.key);else await addRole(selected.id,r.key);setSelected(null)}}>{r.label}</button>})}</div></div></div></section></div>}{notice&&<div className="ma-toast">{notice}</div>}</div>;
}
