import Link from "next/link";
import { ArrowLeft, BarChart3, FileText, Library, Plug, SearchCheck, Settings, SlidersHorizontal, Sparkles } from "lucide-react";

const cards=[
 {title:"Website UI & Theme",desc:"Logo variants, colors, typography, header, footer, mobile layout and module visibility.",href:"/admin/ui-settings",icon:SlidersHorizontal},
 {title:"SEO & Social",desc:"Global SEO defaults, social metadata, indexing, sitemaps and content SEO.",href:"/admin/seo",icon:SearchCheck},
 {title:"Integrations",desc:"Razorpay, Google Maps, Mux and other external services.",href:"/admin/integrations",icon:Plug},
 {title:"Pages & Policies",desc:"Terms, privacy, refund policy, contest policies and custom pages.",href:"/admin/pages",icon:FileText},
 {title:"Media Library",desc:"Manage reusable images and media used across the platform.",href:"/admin/media",icon:Library},
 {title:"Advanced Data",desc:"Direct operational record access for administrators.",href:"/admin/advanced",icon:BarChart3},
];

export default function SettingsHome(){return <main style={{minHeight:"100vh",background:"#f6f7fb",padding:"24px"}}><div style={{maxWidth:1180,margin:"0 auto"}}><Link href="/admin" style={{display:"inline-flex",alignItems:"center",gap:7,fontSize:12,fontWeight:800,color:"#72103a"}}><ArrowLeft size={15}/>Back to Dashboard</Link><div style={{marginTop:18,padding:"28px",borderRadius:24,background:"linear-gradient(120deg,#5f062d,#8b1045 58%,#ba6420)",color:"white",boxShadow:"0 18px 40px rgba(74,20,42,.16)"}}><div style={{display:"flex",gap:12,alignItems:"center"}}><Settings size={28}/><div><small style={{fontSize:9,fontWeight:900,letterSpacing:".13em",color:"#ffd77c"}}>PLATFORM CONFIGURATION</small><h1 style={{margin:"5px 0 6px",fontSize:34}}>Settings</h1><p style={{margin:0,fontSize:13,color:"#f7e9ee"}}>All website, integration, SEO and configuration tools in one place.</p></div></div></div><section style={{marginTop:20,display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(240px,1fr))",gap:14}}>{cards.map(({title,desc,href,icon:Icon})=><Link key={href} href={href} style={{minHeight:170,padding:20,border:"1px solid #e4e5ea",borderRadius:18,background:"white",display:"flex",flexDirection:"column",boxShadow:"0 8px 22px rgba(36,28,34,.05)"}}><div style={{width:42,height:42,borderRadius:13,display:"grid",placeItems:"center",background:"#fff1f6",color:"#861044"}}><Icon size={21}/></div><strong style={{marginTop:24,fontSize:15,color:"#281b22"}}>{title}</strong><span style={{marginTop:6,fontSize:11,lineHeight:1.5,color:"#81717a"}}>{desc}</span></Link>)}</section><div style={{marginTop:18,padding:18,border:"1px solid #ece5e9",borderRadius:16,background:"#fff"}}><div style={{display:"flex",gap:9,alignItems:"center",fontWeight:850,color:"#6f0a36"}}><Sparkles size={18}/>Settings architecture</div><p style={{fontSize:11,lineHeight:1.55,color:"#75666e",marginBottom:0}}>Use this page as the central configuration hub. Day-to-day operational modules remain in their own sidebar groups so settings do not get mixed with content management.</p></div></div></main>}
