"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { Activity, BellRing, BriefcaseBusiness, CalendarHeart, ChevronRight, CreditCard, FileText, Gauge, Image, LayoutDashboard, LifeBuoy, LogOut, Menu, Pencil, Plus, RefreshCw, Search, Settings, ShieldCheck, Tags, Trash2, Trophy, UserCog, UsersRound, Video, WalletCards, X } from "lucide-react";
import { supabase } from "@/lib/supabase";
import { BrandIcon } from "@/components/BrandLogo";

type Section="overview"|"contests"|"contest_categories"|"campaigns"|"submissions"|"events"|"event_categories"|"event_packages"|"businesses"|"business_categories"|"business_plans"|"users"|"payments"|"content"|"support"|"settings";
type Field={key:string;label:string;type?:"text"|"textarea"|"number"|"boolean"|"datetime"|"url"|"json"|"array"|"select";options?:{label:string;value:string}[];placeholder?:string};
type ResourceConfig={table:string;title:string;singular:string;description:string;fields:Field[];list:(r:any)=>string;subtitle?:(r:any)=>string;order?:string};

const NAV:[string,Section,any][]=[
 ["Overview","overview",LayoutDashboard],["Contests","contests",Trophy],["Contest Categories","contest_categories",Tags],["Campaigns","campaigns",Image],["Contest Submissions","submissions",Video],
 ["Events & Requests","events",CalendarHeart],["Event Categories","event_categories",Tags],["Publishing Packages","event_packages",WalletCards],["Businesses","businesses",BriefcaseBusiness],["Business Categories","business_categories",Tags],["Business Plans","business_plans",CreditCard],
 ["Users & Roles","users",UsersRound],["Payments","payments",CreditCard],["CMS & Banners","content",FileText],["Support","support",LifeBuoy],["Settings","settings",Settings]
];
const money=(n:any)=>`₹${Number(n||0).toLocaleString("en-IN")}`;
const slugify=(s:string)=>s.toLowerCase().trim().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"");
const asLocal=(v:any)=>v?new Date(v).toISOString().slice(0,16):"";
const cleanValue=(f:Field,v:any)=>{if(f.type==="number")return v===""?null:Number(v);if(f.type==="boolean")return !!v;if(f.type==="datetime")return v?new Date(v).toISOString():null;if(f.type==="array")return typeof v==="string"?v.split("\n").map((x:string)=>x.trim()).filter(Boolean):v;if(f.type==="json"){if(typeof v!=="string")return v;try{return JSON.parse(v||"{}")}catch{return {}}}return v===""?null:v};

export default function AdminMasterConsole(){
 const [user,setUser]=useState<any>(null),[isAdmin,setIsAdmin]=useState(false),[checking,setChecking]=useState(true),[section,setSection]=useState<Section>("overview"),[drawer,setDrawer]=useState(false),[message,setMessage]=useState("");
 const [email,setEmail]=useState("admin@srigaurnitai.com"),[password,setPassword]=useState("");
 const [data,setData]=useState<Record<string,any[]>>({}),[metrics,setMetrics]=useState<Record<string,number>>({}),[search,setSearch]=useState("");
 const [editor,setEditor]=useState<{cfg:ResourceConfig;row:any|null}|null>(null),[form,setForm]=useState<Record<string,any>>({}),[saving,setSaving]=useState(false);
 const configs=useMemo<Record<string,ResourceConfig>>(()=>({
  contests:{table:"contests",title:"Contests",singular:"Contest",description:"Full control over contest content, rules, eligibility, prizes, dates, banners and public presentation.",order:"created_at",list:r=>r.title,subtitle:r=>`${r.slug} • ${r.is_active?"Active":"Inactive"}`,fields:[
   {key:"title",label:"Contest title"},{key:"slug",label:"URL slug"},{key:"subtitle",label:"Subtitle"},{key:"description",label:"Description",type:"textarea"},{key:"banner_url",label:"Banner image URL",type:"url"},{key:"campaign_type",label:"Campaign type"},{key:"card_badge",label:"Card badge"},{key:"cta_label",label:"CTA button text"},{key:"start_at",label:"Start date/time",type:"datetime"},{key:"submission_close_at",label:"Submission closing date/time",type:"datetime"},{key:"winner_announce_at",label:"Winner announcement",type:"datetime"},{key:"rules",label:"Contest rules",type:"textarea"},{key:"eligibility",label:"Eligibility",type:"textarea"},{key:"judging_criteria",label:"Judging criteria",type:"textarea"},{key:"submission_instructions",label:"Submission instructions",type:"textarea"},{key:"terms",label:"Terms & conditions",type:"textarea"},{key:"min_duration_seconds",label:"Minimum video seconds",type:"number"},{key:"max_duration_seconds",label:"Maximum video seconds",type:"number"},{key:"allowed_formats",label:"Allowed formats — one per line",type:"array"},{key:"participation_fee",label:"Entry fee",type:"number"},{key:"winner_count",label:"Number of winners",type:"number"},{key:"first_prize",label:"First prize",type:"number"},{key:"second_prize",label:"Second prize",type:"number"},{key:"third_prize",label:"Third prize",type:"number"},{key:"additional_prizes",label:"Additional prizes JSON",type:"json"},{key:"faq",label:"FAQ JSON",type:"json"},{key:"theme_start",label:"Theme start color"},{key:"theme_end",label:"Theme end color"},{key:"homepage_order",label:"Homepage order",type:"number"},{key:"public_order",label:"Contest page order",type:"number"},{key:"show_on_homepage",label:"Show on homepage",type:"boolean"},{key:"show_public_entries",label:"Show public entries",type:"boolean"},{key:"is_featured",label:"Featured contest",type:"boolean"},{key:"is_active",label:"Active / published",type:"boolean"},{key:"presentation",label:"Advanced presentation JSON",type:"json"}]},
  contest_categories:{table:"contest_categories",title:"Contest Categories",singular:"Contest Category",description:"Control category names, artwork, rules, visibility and order.",order:"sort_order",list:r=>r.name,subtitle:r=>`${r.slug} • order ${r.sort_order}`,fields:[{key:"name",label:"Name"},{key:"slug",label:"Slug"},{key:"description",label:"Description",type:"textarea"},{key:"image_url",label:"Image URL",type:"url"},{key:"icon",label:"Icon key"},{key:"color",label:"Accent color"},{key:"rules",label:"Default category rules",type:"textarea"},{key:"sort_order",label:"Sort order",type:"number"},{key:"is_active",label:"Active",type:"boolean"},{key:"metadata",label:"Metadata JSON",type:"json"}]},
  campaigns:{table:"campaigns",title:"Campaigns",singular:"Campaign",description:"Control homepage campaigns, mission banners, promotional CTAs and campaign rules.",order:"sort_order",list:r=>r.title,subtitle:r=>`${r.campaign_type} • ${r.is_active?"Active":"Inactive"}`,fields:[{key:"title",label:"Title"},{key:"slug",label:"Slug"},{key:"campaign_type",label:"Campaign type"},{key:"subtitle",label:"Subtitle"},{key:"description",label:"Description",type:"textarea"},{key:"banner_url",label:"Banner image URL",type:"url"},{key:"cta_label",label:"CTA label"},{key:"cta_url",label:"CTA URL"},{key:"rules",label:"Campaign rules",type:"textarea"},{key:"eligibility",label:"Eligibility",type:"textarea"},{key:"terms",label:"Terms",type:"textarea"},{key:"start_at",label:"Starts",type:"datetime"},{key:"end_at",label:"Ends",type:"datetime"},{key:"theme_start",label:"Theme start"},{key:"theme_end",label:"Theme end"},{key:"badge",label:"Badge"},{key:"sort_order",label:"Sort order",type:"number"},{key:"show_on_homepage",label:"Show on homepage",type:"boolean"},{key:"is_active",label:"Active",type:"boolean"},{key:"metadata",label:"Metadata JSON",type:"json"}]},
  event_categories:{table:"event_categories",title:"Event Categories",singular:"Event Category",description:"Control event/service types, pricing, images, rules and terms.",order:"sort_order",list:r=>r.name,subtitle:r=>`${money(r.base_price)} • ${r.is_active?"Active":"Inactive"}`,fields:[{key:"name",label:"Name"},{key:"slug",label:"Slug"},{key:"description",label:"Description",type:"textarea"},{key:"base_price",label:"Base price",type:"number"},{key:"image_url",label:"Image URL",type:"url"},{key:"icon",label:"Icon key"},{key:"rules",label:"Rules",type:"textarea"},{key:"terms",label:"Terms",type:"textarea"},{key:"sort_order",label:"Sort order",type:"number"},{key:"is_active",label:"Active",type:"boolean"},{key:"metadata",label:"Metadata JSON",type:"json"}]},
  event_packages:{table:"event_packages",title:"Publishing Packages",singular:"Publishing Package",description:"Edit publishing package pricing, features, badges, images and terms.",order:"sort_order",list:r=>r.name,subtitle:r=>`${money(r.price_modifier)} modifier`,fields:[{key:"name",label:"Name"},{key:"description",label:"Description",type:"textarea"},{key:"price_modifier",label:"Price modifier",type:"number"},{key:"features",label:"Features — one per line",type:"array"},{key:"badge",label:"Badge"},{key:"image_url",label:"Image URL",type:"url"},{key:"terms",label:"Terms",type:"textarea"},{key:"sort_order",label:"Sort order",type:"number"},{key:"is_active",label:"Active",type:"boolean"},{key:"metadata",label:"Metadata JSON",type:"json"}]},
  business_categories:{table:"business_categories",title:"Business Categories",singular:"Business Category",description:"Manage directory categories, images, rules and public order.",order:"sort_order",list:r=>r.name,subtitle:r=>r.slug,fields:[{key:"name",label:"Name"},{key:"slug",label:"Slug"},{key:"description",label:"Description",type:"textarea"},{key:"image_url",label:"Image URL",type:"url"},{key:"icon",label:"Icon key"},{key:"rules",label:"Listing rules",type:"textarea"},{key:"sort_order",label:"Sort order",type:"number"},{key:"is_active",label:"Active",type:"boolean"},{key:"metadata",label:"Metadata JSON",type:"json"}]},
  business_plans:{table:"business_plans",title:"Business Plans",singular:"Business Plan",description:"Control registration fees, subscriptions, limits, features and promotion rules.",order:"priority",list:r=>r.name,subtitle:r=>`${money(r.monthly_price)}/month • ${r.is_active?"Active":"Inactive"}`,fields:[{key:"name",label:"Plan name"},{key:"description",label:"Description",type:"textarea"},{key:"registration_fee",label:"Registration fee",type:"number"},{key:"monthly_price",label:"Monthly price",type:"number"},{key:"quarterly_price",label:"Quarterly price",type:"number"},{key:"annual_price",label:"Annual price",type:"number"},{key:"promotional_price",label:"Promotional price",type:"number"},{key:"trial_days",label:"Trial days",type:"number"},{key:"features",label:"Features — one per line",type:"array"},{key:"max_images",label:"Maximum images",type:"number"},{key:"allows_video",label:"Allows video",type:"boolean"},{key:"priority",label:"Priority",type:"number"},{key:"badge",label:"Badge"},{key:"terms",label:"Plan terms",type:"textarea"},{key:"is_active",label:"Active",type:"boolean"},{key:"metadata",label:"Metadata JSON",type:"json"}]},
  content:{table:"cms_content",title:"CMS & Banners",singular:"CMS Item",description:"Edit homepage copy, banners, announcements, legal content and application text.",order:"key",list:r=>r.title||r.key,subtitle:r=>r.key,fields:[{key:"key",label:"Content key"},{key:"title",label:"Title"},{key:"body",label:"Body",type:"textarea"},{key:"image_url",label:"Image URL",type:"url"},{key:"link_url",label:"Link URL"},{key:"metadata",label:"Metadata JSON",type:"json"},{key:"is_active",label:"Active",type:"boolean"}]}
 }),[]);
 const load=useCallback(async(u:any)=>{if(!u){setChecking(false);setIsAdmin(false);return}setChecking(true);const {data:role}=await supabase.from("user_roles").select("role").eq("user_id",u.id).eq("role","admin").maybeSingle();if(!role){setIsAdmin(false);setChecking(false);return}setIsAdmin(true);const tables=["profiles","contests","contest_categories","campaigns","contest_submissions","event_submissions","event_categories","event_packages","businesses","business_categories","business_plans","payments","cms_content","support_tickets","user_roles","payout_details"];const rs=await Promise.all(tables.map(t=>supabase.from(t).select("*")));setData(Object.fromEntries(tables.map((t,i)=>[t,rs[i].data||[]])));const counts=await Promise.all(["profiles","contests","contest_submissions","event_submissions","businesses","payments"].map(async t=>[t,(await supabase.from(t).select("*",{head:true,count:"exact"})).count||0]));setMetrics(Object.fromEntries(counts));setChecking(false)},[]);
 useEffect(()=>{supabase.auth.getUser().then(({data})=>{setUser(data.user);load(data.user)});const {data:s}=supabase.auth.onAuthStateChange((_e,s)=>{setUser(s?.user||null);load(s?.user)});return()=>s.subscription.unsubscribe()},[load]);
 async function login(e:FormEvent){e.preventDefault();setMessage("Signing in…");const {error}=await supabase.auth.signInWithPassword({email,password});setMessage(error?error.message:"")}
 function openEditor(cfg:ResourceConfig,row:any|null){const v:any={};cfg.fields.forEach(f=>{let x=row?.[f.key];if(f.type==="datetime")x=asLocal(x);if(f.type==="array"&&Array.isArray(x))x=x.join("\n");if(f.type==="json"&&typeof x!=="string")x=JSON.stringify(x??(f.key==="faq"?[]:{}),null,2);if(f.type==="boolean")x=!!x;v[f.key]=x??""});if(!row&&cfg.fields.some(f=>f.key==="slug"))v.slug="";setForm(v);setEditor({cfg,row})}
 async function saveEditor(e:FormEvent){e.preventDefault();if(!editor)return;setSaving(true);const payload:any={};editor.cfg.fields.forEach(f=>payload[f.key]=cleanValue(f,form[f.key]));if("title" in payload&&"slug" in payload&&!payload.slug)payload.slug=slugify(payload.title);if("name" in payload&&"slug" in payload&&!payload.slug)payload.slug=slugify(payload.name);if(editor.row){const {error}=await supabase.from(editor.cfg.table).update(payload).eq("id",editor.row.id);setMessage(error?.message||`${editor.cfg.singular} updated.`)}else{const {error}=await supabase.from(editor.cfg.table).insert(payload);setMessage(error?.message||`${editor.cfg.singular} created.`)}setSaving(false);setEditor(null);load(user)}
 async function remove(cfg:ResourceConfig,row:any){if(!confirm(`Permanently delete ${cfg.singular} “${cfg.list(row)}”? Related records may also be affected.`))return;const {error}=await supabase.from(cfg.table).delete().eq("id",row.id);setMessage(error?.message||`${cfg.singular} deleted.`);load(user)}
 async function update(table:string,id:string,patch:any){const {error}=await supabase.from(table).update(patch).eq("id",id);setMessage(error?.message||"Updated.");load(user)}
 if(checking)return <Loader text="Loading Admin Control Center"/>;
 if(!user||!isAdmin)return <div className="admin-auth-cover"><form className="admin-auth-card" onSubmit={login}><BrandIcon size={92}/><h1>Administrator Login</h1><p>Full Sri Gaur Nitai platform control.</p><label>Email<input value={email} onChange={e=>setEmail(e.target.value)} type="email"/></label><label>Password<input value={password} onChange={e=>setPassword(e.target.value)} type="password"/></label><button>Login</button>{message&&<p>{message}</p>}</form></div>;
 const cfg=(configs as any)[section] as ResourceConfig|undefined;
 const title=NAV.find(x=>x[1]===section)?.[0]||"Admin";
 return <div className="master-admin">{drawer&&<button className="ma-backdrop" onClick={()=>setDrawer(false)}/>}<aside className={drawer?"ma-side open":"ma-side"}><div className="ma-brand"><BrandIcon size={54}/><div><strong>Sri Gaur Nitai</strong><small>Master Administration</small></div></div><nav>{NAV.map(([l,k,I])=><button className={section===k?"active":""} key={k} onClick={()=>{setSection(k);setDrawer(false)}}><I size={17}/><span>{l}</span></button>)}</nav><button className="ma-signout" onClick={()=>supabase.auth.signOut()}><LogOut size={15}/>Sign out</button></aside><main className="ma-main"><header><button className="ma-menu" onClick={()=>setDrawer(true)}><Menu size={20}/></button><div><h1>{title}</h1><p>Administrator has full control over public presentation, commercial rules and operational data.</p></div><div className="ma-head-actions"><button onClick={()=>load(user)}><RefreshCw size={14}/>Refresh</button><a href="/" target="_blank">Open App <ChevronRight size={14}/></a></div></header><div className="ma-content">
 {section==="overview"&&<Overview metrics={metrics} data={data} jump={setSection}/>} 
 {cfg&&<ResourceManager cfg={cfg} rows={data[cfg.table]||[]} search={search} setSearch={setSearch} edit={r=>openEditor(cfg,r)} add={()=>openEditor(cfg,null)} remove={r=>remove(cfg,r)}/>} 
 {section==="submissions"&&<Moderation title="Contest Submissions" rows={data.contest_submissions||[]} actions={(r:any)=><><button onClick={()=>update("contest_submissions",r.id,{status:"approved",reviewed_at:new Date().toISOString(),reviewed_by:user.id})}>Approve</button><button onClick={()=>update("contest_submissions",r.id,{status:"shortlisted"})}>Shortlist</button><button className="danger" onClick={()=>update("contest_submissions",r.id,{status:"rejected"})}>Reject</button></>}/>} 
 {section==="events"&&<Moderation title="Event Requests" rows={data.event_submissions||[]} actions={(r:any)=><><button onClick={()=>update("event_submissions",r.id,{status:"approved"})}>Approve</button><button onClick={()=>update("event_submissions",r.id,{status:"scheduled"})}>Schedule</button><button onClick={()=>update("event_submissions",r.id,{status:"published"})}>Publish</button><button className="danger" onClick={()=>update("event_submissions",r.id,{status:"rejected"})}>Reject</button></>}/>} 
 {section==="businesses"&&<Moderation title="Business Listings" rows={data.businesses||[]} actions={(r:any)=><><button onClick={()=>update("businesses",r.id,{status:"approved"})}>Approve</button><button onClick={()=>update("businesses",r.id,{is_featured:!r.is_featured})}>{r.is_featured?"Unfeature":"Feature"}</button><a href={`/businesses/${r.slug}`} target="_blank">View</a><button className="danger" onClick={()=>update("businesses",r.id,{status:"suspended"})}>Suspend</button></>}/>} 
 {section==="users"&&<UsersPanel profiles={data.profiles||[]} roles={data.user_roles||[]} refresh={()=>load(user)}/>} 
 {section==="payments"&&<Moderation title="Payments" rows={data.payments||[]} actions={(r:any)=><><button onClick={()=>update("payments",r.id,{status:"paid",paid_at:new Date().toISOString()})}>Mark Paid</button><button className="danger" onClick={()=>update("payments",r.id,{status:"refunded"})}>Refund</button></>}/>} 
 {section==="support"&&<Moderation title="Support Tickets" rows={data.support_tickets||[]} actions={(r:any)=><><button onClick={()=>update("support_tickets",r.id,{status:"in_progress"})}>In Progress</button><button onClick={()=>update("support_tickets",r.id,{status:"resolved"})}>Resolve</button></>}/>} 
 {section==="settings"&&<SettingsPanel data={data}/>} 
 </div>{message&&<div className="ma-toast">{message}<button onClick={()=>setMessage("")}><X size={14}/></button></div>}</main>{editor&&<Editor editor={editor} form={form} setForm={setForm} close={()=>setEditor(null)} save={saveEditor} saving={saving}/>}</div>
}

function Loader({text}:{text:string}){return <div className="ma-loader"><BrandIcon size={132}/><strong>{text}</strong><span><i/></span></div>}
function Overview({metrics,data,jump}:{metrics:any;data:any;jump:(s:Section)=>void}){const rev=(data.payments||[]).filter((p:any)=>p.status==="paid").reduce((s:number,p:any)=>s+Number(p.amount||0),0);const cards=[["Users",metrics.profiles,UsersRound],["Contests",metrics.contests,Trophy],["Entries",metrics.contest_submissions,Video],["Event Requests",metrics.event_submissions,CalendarHeart],["Businesses",metrics.businesses,BriefcaseBusiness],["Paid Revenue",money(rev),CreditCard]];return <><div className="ma-kpis">{cards.map(([l,v,I]:any)=><article key={l}><I/><span>{l}</span><strong>{v||0}</strong></article>)}</div><section className="ma-panel"><div className="ma-panel-head"><div><h2>Full Control Shortcuts</h2><p>Edit what users see and how the platform operates.</p></div></div><div className="ma-shortcuts">{[["Contest Rules & Presentation","contests",Trophy],["Campaigns & Home Banners","campaigns",Image],["Event Categories & Pricing","event_categories",CalendarHeart],["Publishing Packages","event_packages",WalletCards],["Business Rules & Plans","business_plans",BriefcaseBusiness],["CMS & Legal Content","content",FileText]].map(([l,s,I]:any)=><button key={l} onClick={()=>jump(s)}><I/><strong>{l}</strong><span>Open editor</span></button>)}</div></section></>}
function ResourceManager({cfg,rows,search,setSearch,edit,add,remove}:{cfg:ResourceConfig;rows:any[];search:string;setSearch:(x:string)=>void;edit:(r:any)=>void;add:()=>void;remove:(r:any)=>void}){const filtered=rows.filter(r=>!search||cfg.list(r).toLowerCase().includes(search.toLowerCase())||(cfg.subtitle?.(r)||"").toLowerCase().includes(search.toLowerCase()));return <><div className="ma-section-head"><div><h2>{cfg.title}</h2><p>{cfg.description}</p></div><button className="primary" onClick={add}><Plus size={15}/>Add {cfg.singular}</button></div><div className="ma-search"><Search size={16}/><input placeholder={`Search ${cfg.title.toLowerCase()}…`} value={search} onChange={e=>setSearch(e.target.value)}/></div><div className="ma-resource-list">{filtered.map(r=><article key={r.id}><div><strong>{cfg.list(r)}</strong><span>{cfg.subtitle?.(r)||r.id}</span></div><div className="ma-actions"><button onClick={()=>edit(r)}><Pencil size={14}/>Edit</button><button className="danger" onClick={()=>remove(r)}><Trash2 size={14}/>Delete</button></div></article>)}</div></>}
function Editor({editor,form,setForm,close,save,saving}:{editor:any;form:any;setForm:any;close:()=>void;save:(e:FormEvent)=>void;saving:boolean}){return <div className="ma-modal-bg"><form className="ma-modal" onSubmit={save}><header><div><h2>{editor.row?`Edit ${editor.cfg.singular}`:`Add ${editor.cfg.singular}`}</h2><p>Changes are written directly to the production database and public application.</p></div><button type="button" onClick={close}><X/></button></header><div className="ma-form-grid">{editor.cfg.fields.map((f:Field)=>{const v=form[f.key];return <label key={f.key} className={f.type==="textarea"||f.type==="json"||f.type==="array"?"wide":""}><span>{f.label}</span>{f.type==="boolean"?<input type="checkbox" checked={!!v} onChange={e=>setForm({...form,[f.key]:e.target.checked})}/>:f.type==="textarea"||f.type==="json"||f.type==="array"?<textarea rows={f.type==="json"?6:4} value={v??""} onChange={e=>setForm({...form,[f.key]:e.target.value})}/>:<input type={f.type==="number"?"number":f.type==="datetime"?"datetime-local":f.type==="url"?"url":"text"} value={v??""} onChange={e=>setForm({...form,[f.key]:e.target.value})}/>}</label>})}</div><footer><button type="button" onClick={close}>Cancel</button><button className="primary" disabled={saving}>{saving?"Saving…":"Save Changes"}</button></footer></form></div>}
function Moderation({title,rows,actions}:{title:string;rows:any[];actions:(r:any)=>any}){return <><div className="ma-section-head"><div><h2>{title}</h2><p>Operational records with direct administrative actions.</p></div></div><div className="ma-resource-list">{rows.map(r=><article key={r.id}><div><strong>{r.title||r.name||r.subject_name||r.reference_code||r.purpose||"Record"}</strong><span>{r.status||r.email||r.id}</span></div><div className="ma-actions">{actions(r)}</div></article>)}</div></>}
function UsersPanel({profiles,roles,refresh}:{profiles:any[];roles:any[];refresh:()=>void}){const roleMap=roles.reduce((a:any,r:any)=>{(a[r.user_id]??=[]).push(r.role);return a},{});async function addRole(id:string,role:string){await supabase.from("user_roles").upsert({user_id:id,role});refresh()}return <><div className="ma-section-head"><div><h2>Users & Roles</h2><p>Inspect users and grant business/moderator/admin roles.</p></div></div><div className="ma-resource-list">{profiles.map(p=><article key={p.id}><div><strong>{p.full_name||p.email||"User"}</strong><span>{p.email} • {(roleMap[p.id]||["user"]).join(", ")}</span></div><div className="ma-actions"><button onClick={()=>addRole(p.id,"business")}>Business</button><button onClick={()=>addRole(p.id,"moderator")}>Moderator</button><button onClick={()=>addRole(p.id,"admin")}>Admin</button></div></article>)}</div></>}
function SettingsPanel({data}:{data:any}){return <><div className="ma-section-head"><div><h2>Platform Settings</h2><p>Operational overview. Content/rules are edited in their dedicated modules.</p></div></div><div className="ma-kpis"><article><Gauge/><span>Environment</span><strong>Production</strong></article><article><ShieldCheck/><span>Admin RLS</span><strong>Enabled</strong></article><article><Activity/><span>Campaigns</span><strong>{(data.campaigns||[]).length}</strong></article><article><BellRing/><span>CMS items</span><strong>{(data.cms_content||[]).length}</strong></article></div></>}
