package com.srigaurnitai.app;

import android.app.Activity;
import android.content.SharedPreferences;
import android.graphics.Color;
import android.graphics.Typeface;
import android.graphics.drawable.GradientDrawable;
import android.view.Gravity;
import android.widget.*;

public class LaunchFlow {
  private final Activity a; private final FrameLayout root; private final SharedPreferences prefs; private FrameLayout layer; private final int maroon=0xff700831,gold=0xffcd932e,cream=0xfffcf8f0,border=0xffeddcbe,muted=0xff75676b;
  public LaunchFlow(Activity a,FrameLayout root,SharedPreferences p){this.a=a;this.root=root;this.prefs=p;}
  private int dp(int v){return Math.round(v*a.getResources().getDisplayMetrics().density);} private GradientDrawable round(int c,int r){GradientDrawable d=new GradientDrawable();d.setColor(c);d.setCornerRadius(dp(r));return d;}
  public boolean visible(){return layer!=null;} public void dismiss(){prefs.edit().putBoolean("onboarding_complete_v4",true).apply();hide();}
  public void show(){layer=new FrameLayout(a);GradientDrawable bg=new GradientDrawable(GradientDrawable.Orientation.TL_BR,new int[]{0xfffffbf2,0xfff8e5c2,0xfff4d6de});layer.setBackground(bg);layer.setElevation(dp(50));root.addView(layer,new FrameLayout.LayoutParams(-1,-1));ImageView logo=new ImageView(a);logo.setImageResource(R.drawable.sgn_mark);logo.setScaleType(ImageView.ScaleType.CENTER_INSIDE);FrameLayout.LayoutParams lp=new FrameLayout.LayoutParams(dp(245),dp(245),Gravity.CENTER);lp.bottomMargin=dp(70);layer.addView(logo,lp);TextView l=new TextView(a);l.setText("Preparing your devotional space…");l.setTextColor(maroon);l.setTextSize(12);l.setGravity(Gravity.CENTER);l.setBackground(round(0xeeffffff,18));FrameLayout.LayoutParams ll=new FrameLayout.LayoutParams(dp(235),dp(40),Gravity.BOTTOM|Gravity.CENTER_HORIZONTAL);ll.bottomMargin=dp(38);layer.addView(l,ll);root.postDelayed(()->{if(prefs.getBoolean("onboarding_complete_v4",false))hide();else page(0);},1200);}
  private FrameLayout visual(int i){FrameLayout b=new FrameLayout(a);GradientDrawable g=new GradientDrawable(GradientDrawable.Orientation.TL_BR,i==0?new int[]{0xfffffbef,0xfff5dda6}:i==1?new int[]{0xfffffaf3,0xfff0d4c2}:new int[]{0xfffffbf4,0xffeedde5});g.setCornerRadius(dp(30));g.setStroke(dp(1),border);b.setBackground(g);ImageView logo=new ImageView(a);logo.setImageResource(R.drawable.sgn_mark);logo.setScaleType(ImageView.ScaleType.CENTER_INSIDE);FrameLayout.LayoutParams lp=new FrameLayout.LayoutParams(dp(86),dp(86),Gravity.TOP|Gravity.CENTER_HORIZONTAL);lp.topMargin=dp(14);b.addView(logo,lp);int hero=i==0?R.drawable.nav_contests:i==1?R.drawable.nav_events:R.drawable.nav_businesses;ImageView h=new ImageView(a);h.setImageResource(hero);h.setPadding(dp(24),dp(24),dp(24),dp(24));h.setBackground(round(0xffffffff,32));FrameLayout.LayoutParams hp=new FrameLayout.LayoutParams(dp(150),dp(150),Gravity.CENTER);b.addView(h,hp);int[][] sats={{R.drawable.nav_winners,R.drawable.nav_videos,R.drawable.nav_account},{R.drawable.nav_events,R.drawable.nav_videos,R.drawable.nav_support},{R.drawable.nav_journal,R.drawable.nav_quotes,R.drawable.nav_support}};LinearLayout row=new LinearLayout(a);row.setGravity(Gravity.CENTER);for(int id:sats[i]){ImageView x=new ImageView(a);x.setImageResource(id);x.setPadding(dp(12),dp(12),dp(12),dp(12));x.setBackground(round(0xf8ffffff,18));LinearLayout.LayoutParams xp=new LinearLayout.LayoutParams(dp(68),dp(68));xp.leftMargin=dp(7);xp.rightMargin=dp(7);row.addView(x,xp);}FrameLayout.LayoutParams rp=new FrameLayout.LayoutParams(-1,dp(74),Gravity.BOTTOM);rp.bottomMargin=dp(22);b.addView(row,rp);return b;}
  private void page(int i){layer.removeAllViews();layer.setBackgroundColor(cream);LinearLayout p=new LinearLayout(a);p.setOrientation(LinearLayout.VERTICAL);p.setPadding(dp(18),dp(16),dp(18),dp(12));layer.addView(p,new FrameLayout.LayoutParams(-1,-1));TextView skip=new TextView(a);skip.setText("Skip");skip.setTextColor(maroon);skip.setGravity(Gravity.RIGHT);skip.setTextSize(13);skip.setPadding(0,dp(6),dp(6),dp(8));skip.setOnClickListener(v->dismiss());p.addView(skip,new LinearLayout.LayoutParams(-1,dp(42)));LinearLayout.LayoutParams vp=new LinearLayout.LayoutParams(-1,0,1);p.addView(visual(i),vp);String[] t={"Share Your Devotion","Celebrate Divine Moments","Discover Community & Support"};String[] d={"Join sacred contests, submit performances and follow every stage from review to winners.","Publish birthdays, weddings and family celebrations through Sri Gaur Nitai event services.","Explore trusted businesses, devotional articles, daily quotes, public videos and support."};TextView dots=new TextView(a);dots.setText(i==0?"●  ○  ○":i==1?"○  ●  ○":"○  ○  ●");dots.setTextColor(maroon);dots.setTextSize(18);dots.setGravity(Gravity.CENTER);p.addView(dots,new LinearLayout.LayoutParams(-1,dp(34)));TextView title=new TextView(a);title.setText(t[i]);title.setTextColor(maroon);title.setTypeface(Typeface.SERIF,Typeface.BOLD);title.setTextSize(26);title.setGravity(Gravity.CENTER);p.addView(title);TextView desc=new TextView(a);desc.setText(d[i]);desc.setTextColor(muted);desc.setTextSize(13.5f);desc.setGravity(Gravity.CENTER);desc.setPadding(dp(8),dp(5),dp(8),dp(10));p.addView(desc);TextView next=new TextView(a);next.setText(i==2?"Get Started  →":"Next  →");next.setTextColor(Color.WHITE);next.setTextSize(16);next.setTypeface(Typeface.DEFAULT,Typeface.BOLD);next.setGravity(Gravity.CENTER);GradientDrawable nb=new GradientDrawable(GradientDrawable.Orientation.LEFT_RIGHT,new int[]{maroon,0xff981546});nb.setCornerRadius(dp(27));next.setBackground(nb);LinearLayout.LayoutParams np=new LinearLayout.LayoutParams(-1,dp(54));np.topMargin=dp(4);p.addView(next,np);next.setOnClickListener(v->{if(i<2)page(i+1);else dismiss();});}
  private void hide(){if(layer==null)return;FrameLayout old=layer;layer=null;old.animate().alpha(0).setDuration(220).withEndAction(()->root.removeView(old)).start();}
}
