"use client";

import Link from "next/link";
import { useEffect,useState } from "react";
import { ArrowLeft,ExternalLink,Save,SearchCheck,ShieldCheck } from "lucide-react";
import { supabase } from "@/lib/supabase";

type Kind="contest"|"event"|"business";
const config={
 contest:{table:"contests",label:"Contest",back:"/admin",name:"title",publicPath:"/contests/"},
 event:{table:"event_categories",label:"Event",back:"/admin",name:"name",publicPath:"/events/"},
 business:{table:"businesses",label:"Business Listing",back:"/admin",name:"name",publicPath:"/businesses/"},
} as const;

export default function ListingSeoEditor({kind,id}:{kind:Kind;id:string}){
 const cfg=config[kind];
 const [user,setUser]=useState<any>(null),[allowed,setAllowed]=useState(false),[loading,setLoading]=useState(true),[row,setRow]=useState<any>(null),[notice,setNotice]=useState("");
 useEffect(()=>{(async()=>{const {data:{user:u}}=await supabase.auth.getUser();setUser(u);if(!u){setLoading(false);return}const {data:roles}=await supabase.from("user_roles").select("role").eq("user_id",u.id);const ok=(roles||[]).some((r:any)=>r.role==="admin"||r.role==="content_manager");setAllowed(ok);if(!ok){setLoading(false);return}const {data}=await supabase.from(cfg.table).select("*").eq("id",id).maybeSingle();setRow({...data,seo_keywords:Array.isArray(data?.seo_keywords)?data.seo_keywords.join(", "):data?.seo_keywords||"",seo_schema:typeof data?.seo_schema==="string"?data.seo_schema:JSON.stringify(data?.seo_schema||{},null,2)});setLoading(false)})()},[cfg.table,id]);
 async function save(){if(!row)return;let schema=row.seo_schema;try{schema=typeof schema==="string"?JSON.parse(schema||"{}"):schema}catch{return setNotice("Structured data JSON is invalid.")}const payload={seo_title:row.seo_title||null,seo_description:row.seo_description||null,seo_keywords:typeof row.seo_keywords==="string"?row.seo_keywords.split(",").map((x:string)=>x.trim()).filter(Boolean):row.seo_keywords||[],seo_canonical_url:row.seo_canonical_url||null,seo_og_title:row.seo_og_title||null,seo_og_description:row.seo_og_description||null,seo_og_image_url:row.seo_og_image_url||null,seo_noindex:!!row.seo_noindex,seo_schema:schema};const {error}=await supabase.from(cfg.table).update(payload).eq("id",id);setNotice(error?.message||`${cfg.label} SEO saved.`)}
 if(loading)return <main className="seo-record-page"><div className="seo-record-loading"><SearchCheck/><strong>Loading {cfg.label} SEO…</strong></div></main>;
 if(!user||!allowed)return <main className="seo-record-page"><div className="seo-record-denied"><ShieldCheck/><h1>Restricted</h1><p>Administrator or Content Manager access is required.</p><Link href="/admin">Back to Admin</Link></div></main>;
 if(!row)return <main className="seo-record-page"><div className="seo-record-denied"><h1>{cfg.label} not found</h1><Link href="/admin">Back to Admin</Link></div></main>;
 const title=row[cfg.name]||cfg.label;const publicUrl=row.slug?`${cfg.publicPath}${row.slug}`:"";
 return <main className="seo-record-page"><div className="seo-record-wrap"><header className="seo-record-header"><div><Link href={cfg.back}><ArrowLeft size={15}/>Back to Admin</Link><small>ADVANCED SEO · {cfg.label.toUpperCase()}</small><h1>{title}</h1><p>SEO for this specific {cfg.label.toLowerCase()} only. Global website SEO remains in the SEO Control Center.</p></div><div className="seo-record-head-actions">{publicUrl&&<a href={publicUrl} target="_blank" rel="noreferrer"><ExternalLink size={15}/>View public page</a>}<button onClick={save}><Save size={15}/>Save SEO</button></div></header><section className="seo-record-preview"><span>Search preview</span><strong>{row.seo_title||title}</strong><p>{row.seo_description||row.description||"Add a focused meta description for this page."}</p></section><section className="seo-record-form"><label className="wide">SEO title<input value={row.seo_title||""} onChange={e=>setRow({...row,seo_title:e.target.value})} maxLength={70}/><small>{(row.seo_title||"").length}/70</small></label><label className="wide">Meta description<textarea rows={3} value={row.seo_description||""} onChange={e=>setRow({...row,seo_description:e.target.value})} maxLength={180}/><small>{(row.seo_description||"").length}/180</small></label><label className="wide">Keywords<input value={row.seo_keywords||""} onChange={e=>setRow({...row,seo_keywords:e.target.value})} placeholder="keyword one, keyword two"/></label><label className="wide">Canonical URL<input value={row.seo_canonical_url||""} onChange={e=>setRow({...row,seo_canonical_url:e.target.value})}/></label><label>Social / Open Graph title<input value={row.seo_og_title||""} onChange={e=>setRow({...row,seo_og_title:e.target.value})}/></label><label>Social share image URL<input value={row.seo_og_image_url||""} onChange={e=>setRow({...row,seo_og_image_url:e.target.value})}/></label><label className="wide">Social / Open Graph description<textarea rows={3} value={row.seo_og_description||""} onChange={e=>setRow({...row,seo_og_description:e.target.value})}/></label><label className="seo-record-check wide"><input type="checkbox" checked={!!row.seo_noindex} onChange={e=>setRow({...row,seo_noindex:e.target.checked})}/><span><strong>Hide from search engines</strong><small>Sets this individual page to noindex.</small></span></label><label className="wide">Structured data / Schema JSON<textarea rows={9} value={row.seo_schema||"{}"} onChange={e=>setRow({...row,seo_schema:e.target.value})}/></label></section><footer className="seo-record-footer"><button onClick={save}><Save size={15}/>Save {cfg.label} SEO</button></footer>{notice&&<div className="seo-record-toast">{notice}</div>}</div></main>
}
