"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";
import { Bell, BriefcaseBusiness, CheckCircle2, ChevronRight, CircleUserRound, CreditCard, KeyRound, LogOut, Mail, Phone, ShieldCheck, Trophy, Upload, WalletCards } from "lucide-react";
import { supabase } from "@/lib/supabase";

const emptyDashboard = { profile:null as any, contests:[] as any[], events:[] as any[], businesses:[] as any[], payments:[] as any[], notifications:[] as any[], payout:null as any };
const defaultAuthConfig={email_password_enabled:true,email_otp_enabled:true,sms_login_enabled:false,sms_signup_enabled:false,require_email_verification:true,require_phone_verification:false};
type Mode = "login"|"register"|"verify-email"|"email-otp"|"phone"|"verify-phone"|"phone-signup"|"verify-phone-signup"|"forgot";

export default function AccountPage() {
  const [mode,setMode]=useState<Mode>("login");
  const [email,setEmail]=useState(""); const [phone,setPhone]=useState(""); const [password,setPassword]=useState(""); const [name,setName]=useState(""); const [otp,setOtp]=useState("");
  const [message,setMessage]=useState(""); const [busy,setBusy]=useState(false); const [user,setUser]=useState<any>(null); const [dash,setDash]=useState(emptyDashboard); const [loadingDash,setLoadingDash]=useState(false); const [authConfig,setAuthConfig]=useState(defaultAuthConfig);

  const loadDashboard=useCallback(async(u:any)=>{
    if(!u)return; setLoadingDash(true);
    const [profile,contests,events,businesses,payments,notifications,payout]=await Promise.all([
      supabase.from("profiles").select("*").eq("id",u.id).maybeSingle(),
      supabase.from("contest_submissions").select("id,reference_code,title,status,submitted_at,contests(title,slug)").eq("user_id",u.id).order("submitted_at",{ascending:false}),
      supabase.from("event_submissions").select("id,reference_code,title,subject_name,status,requested_publish_date,youtube_url,event_categories(name)").eq("user_id",u.id).order("created_at",{ascending:false}),
      supabase.from("businesses").select("id,name,slug,status,subscription_expires_at,is_featured").eq("owner_user_id",u.id).order("created_at",{ascending:false}),
      supabase.from("payments").select("id,purpose,amount,status,transaction_id,created_at,receipt_url").eq("user_id",u.id).order("created_at",{ascending:false}).limit(20),
      supabase.from("notifications").select("id,title,body,read_at,created_at,action_url").eq("user_id",u.id).order("created_at",{ascending:false}).limit(20),
      supabase.from("payout_details").select("account_holder_name,bank_name,ifsc,upi_id,updated_at").eq("user_id",u.id).maybeSingle()
    ]);
    setDash({profile:profile.data,contests:contests.data||[],events:events.data||[],businesses:businesses.data||[],payments:payments.data||[],notifications:notifications.data||[],payout:payout.data}); setLoadingDash(false);
  },[]);

  useEffect(()=>{
    supabase.from("integration_configs").select("public_config").eq("provider","authentication").maybeSingle().then(({data})=>setAuthConfig({...defaultAuthConfig,...(data?.public_config||{})}));
    supabase.auth.getUser().then(({data})=>{setUser(data.user||null); if(data.user)loadDashboard(data.user)});
    const {data}=supabase.auth.onAuthStateChange((_e,s)=>{setUser(s?.user||null); if(s?.user)loadDashboard(s.user); else setDash(emptyDashboard)}); return()=>data.subscription.unsubscribe()
  },[loadDashboard]);

  async function run(fn:()=>Promise<void>){setBusy(true);setMessage("");try{await fn()}catch(e:any){setMessage(e.message||"Something went wrong.")}finally{setBusy(false)}}
  function passwordLogin(e:FormEvent){e.preventDefault();run(async()=>{if(!authConfig.email_password_enabled)throw new Error("Password login is currently disabled.");const {error}=await supabase.auth.signInWithPassword({email,password});if(error)throw error;setMessage("Signed in successfully.")})}
  function sendRegistrationOtp(){run(async()=>{if(!email||!password||!name)throw new Error("Name, email and password are required.");if(authConfig.require_email_verification){const {error}=await supabase.auth.signInWithOtp({email,options:{shouldCreateUser:true,data:{full_name:name,mobile:phone}}});if(error)throw error;setMode("verify-email");setMessage("A 6-digit verification code has been sent to your email.")}else{const {error}=await supabase.auth.signUp({email,password,options:{data:{full_name:name,mobile:phone}}});if(error)throw error;setMessage("Account created successfully.")}})}
  function sendEmailLoginOtp(){run(async()=>{if(!authConfig.email_otp_enabled)throw new Error("Email OTP login is currently disabled.");if(!email)throw new Error("Enter your registered email address.");const {error}=await supabase.auth.signInWithOtp({email,options:{shouldCreateUser:false}});if(error)throw error;setMode("email-otp");setMessage("Enter the code sent to your registered email.")})}
  function verifyEmailOtp(){run(async()=>{const {error}=await supabase.auth.verifyOtp({email,token:otp,type:"email"});if(error)throw error;if(mode==="verify-email"&&password){const {error:updateError}=await supabase.auth.updateUser({password});if(updateError)throw updateError}setMessage("Email verified successfully.")})}
  function sendPhoneOtp(){run(async()=>{if(!authConfig.sms_login_enabled)throw new Error("SMS login is currently disabled.");const normalized=phone.startsWith("+")?phone:`+91${phone.replace(/\D/g,"")}`;const {error}=await supabase.auth.signInWithOtp({phone:normalized,options:{shouldCreateUser:false}});if(error)throw error;setPhone(normalized);setMode("verify-phone");setMessage("OTP sent to your phone.")})}
  function sendPhoneSignupOtp(){run(async()=>{if(!authConfig.sms_signup_enabled)throw new Error("SMS registration is currently disabled.");if(!name||!phone)throw new Error("Name and mobile number are required.");const normalized=phone.startsWith("+")?phone:`+91${phone.replace(/\D/g,"")}`;const {error}=await supabase.auth.signInWithOtp({phone:normalized,options:{shouldCreateUser:true,data:{full_name:name,email}}});if(error)throw error;setPhone(normalized);setMode("verify-phone-signup");setMessage("Registration OTP sent to your phone.")})}
  function verifyPhoneOtp(){run(async()=>{const {error}=await supabase.auth.verifyOtp({phone,token:otp,type:"sms"});if(error)throw error;if(mode==="verify-phone-signup"&&password){const {error:updateError}=await supabase.auth.updateUser({password});if(updateError)throw updateError}setMessage(mode==="verify-phone-signup"?"Mobile verified and account created.":"Phone verified and signed in.")})}
  function forgot(){run(async()=>{const {error}=await supabase.auth.resetPasswordForEmail(email,{redirectTo:`${window.location.origin}/account/reset-password`});if(error)throw error;setMessage("Password reset instructions have been sent to your email.")})}
  async function saveProfile(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!user)return;const fd=new FormData(e.currentTarget);run(async()=>{const {error}=await supabase.from("profiles").update({full_name:String(fd.get("full_name")||""),mobile:String(fd.get("mobile")||""),city:String(fd.get("city")||""),state:String(fd.get("state")||"")}).eq("id",user.id);if(error)throw error;await loadDashboard(user);setMessage("Profile updated.")})}
  async function savePayout(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!user)return;const fd=new FormData(e.currentTarget);run(async()=>{const {error}=await supabase.from("payout_details").upsert({user_id:user.id,account_holder_name:String(fd.get("account_holder_name")||""),bank_name:String(fd.get("bank_name")||""),ifsc:String(fd.get("ifsc")||""),upi_id:String(fd.get("upi_id")||"")});if(error)throw error;await loadDashboard(user);setMessage("Payout details saved securely.")})}

  if(user)return <div className="page account-page"><section className="account-hero"><div className="account-avatar"><CircleUserRound size={38}/></div><div><span className="verified-pill"><CheckCircle2 size={13}/> Verified account</span><h1>{dash.profile?.full_name||user.user_metadata?.full_name||"Sri Gaur Nitai Member"}</h1><p>{user.email||user.phone}</p></div><button className="btn soft-btn" onClick={()=>supabase.auth.signOut()}><LogOut size={15}/> Sign out</button></section>
    <div className="account-stat-grid"><div><strong>{dash.contests.length}</strong><span>Contest entries</span></div><div><strong>{dash.events.length}</strong><span>Event requests</span></div><div><strong>{dash.businesses.length}</strong><span>Businesses</span></div><div><strong>{dash.payments.length}</strong><span>Transactions</span></div></div>
    {loadingDash&&<div className="inline-loading">Loading your account…</div>}
    <section className="account-menu-grid"><a href="#contests"><Trophy/><span><strong>My Contests</strong><small>Submissions, status and prizes</small></span><ChevronRight/></a><a href="#events"><Upload/><span><strong>My Events</strong><small>Publishing requests and YouTube links</small></span><ChevronRight/></a><a href="#businesses"><BriefcaseBusiness/><span><strong>My Businesses</strong><small>Listings and subscription expiry</small></span><ChevronRight/></a><a href="#payments"><CreditCard/><span><strong>Payments & Invoices</strong><small>Transaction history</small></span><ChevronRight/></a><a href="#payout"><WalletCards/><span><strong>Payout Details</strong><small>Bank and UPI information</small></span><ChevronRight/></a><a href="#notifications"><Bell/><span><strong>Notifications</strong><small>Important account activity</small></span><ChevronRight/></a></section>
    <section className="section account-section" id="contests"><div className="section-head"><div><h2>My Contests</h2><p>Live submission tracking</p></div></div>{dash.contests.length?dash.contests.map((x:any)=><div className="account-list-row" key={x.id}><div><strong>{x.contests?.title||x.title}</strong><span>{x.reference_code}</span></div><em className={`status-pill ${x.status}`}>{String(x.status).replaceAll("_"," ")}</em></div>):<div className="empty-mini">No contest submissions yet.</div>}</section>
    <section className="section account-section" id="events"><div className="section-head"><div><h2>My Events</h2><p>Publishing and approval status</p></div></div>{dash.events.length?dash.events.map((x:any)=><div className="account-list-row" key={x.id}><div><strong>{x.title||x.subject_name}</strong><span>{x.event_categories?.name} • {x.reference_code}</span></div><div>{x.youtube_url?<a className="tiny-link" href={x.youtube_url} target="_blank">Watch</a>:<em className={`status-pill ${x.status}`}>{String(x.status).replaceAll("_"," ")}</em>}</div></div>):<div className="empty-mini">No event requests yet.</div>}</section>
    <section className="section account-section" id="businesses"><div className="section-head"><div><h2>My Businesses</h2><p>Manage your listings</p></div><a className="section-link" href="/businesses/register">Add business</a></div>{dash.businesses.length?dash.businesses.map((x:any)=><a className="account-list-row" href={`/businesses/${x.slug}`} key={x.id}><div><strong>{x.name}</strong><span>{x.subscription_expires_at?`Plan until ${new Date(x.subscription_expires_at).toLocaleDateString("en-IN")}`:"No active subscription"}</span></div><em className={`status-pill ${x.status}`}>{x.status}</em></a>):<div className="empty-mini">You have not listed a business yet.</div>}</section>
    <section className="section account-section" id="payments"><div className="section-head"><div><h2>Payments</h2><p>Transactions and receipts</p></div></div>{dash.payments.length?dash.payments.map((x:any)=><div className="account-list-row" key={x.id}><div><strong>₹{Number(x.amount).toLocaleString("en-IN")} • {String(x.purpose).replaceAll("_"," ")}</strong><span>{new Date(x.created_at).toLocaleDateString("en-IN")} {x.transaction_id?`• ${x.transaction_id}`:""}</span></div><em className={`status-pill ${x.status}`}>{x.status}</em></div>):<div className="empty-mini">No payments recorded.</div>}</section>
    <section className="section account-two-col"><form className="form-card" onSubmit={saveProfile}><h2>Profile</h2><div className="field"><label>Full name</label><input name="full_name" defaultValue={dash.profile?.full_name||""}/></div><div className="field"><label>Mobile</label><input name="mobile" defaultValue={dash.profile?.mobile||""}/></div><div className="field"><label>City</label><input name="city" defaultValue={dash.profile?.city||""}/></div><div className="field"><label>State</label><input name="state" defaultValue={dash.profile?.state||""}/></div><button className="btn btn-primary" disabled={busy}>Save Profile</button></form><form className="form-card" id="payout" onSubmit={savePayout}><h2>Payout Details</h2><p className="form-note"><ShieldCheck size={14}/> Restricted to you and administrators.</p><div className="field"><label>Account holder</label><input name="account_holder_name" defaultValue={dash.payout?.account_holder_name||""}/></div><div className="field"><label>Bank name</label><input name="bank_name" defaultValue={dash.payout?.bank_name||""}/></div><div className="field"><label>IFSC</label><input name="ifsc" defaultValue={dash.payout?.ifsc||""}/></div><div className="field"><label>UPI ID</label><input name="upi_id" defaultValue={dash.payout?.upi_id||""}/></div><button className="btn btn-primary" disabled={busy}>Save Payout Details</button></form></section>
    <section className="section account-section" id="notifications"><div className="section-head"><div><h2>Notifications</h2></div></div>{dash.notifications.length?dash.notifications.map((n:any)=><div className="notification-row" key={n.id}><Bell size={17}/><div><strong>{n.title}</strong><p>{n.body}</p><span>{new Date(n.created_at).toLocaleString("en-IN")}</span></div></div>):<div className="empty-mini">No notifications yet.</div>}</section>{message&&<div className="toast-message">{message}</div>}
  </div>;

  const verifyMode=mode==="verify-email"||mode==="email-otp"||mode==="verify-phone"||mode==="verify-phone-signup";
  return <div className="page auth-page"><section className="auth-shell"><div className="auth-intro"><CircleUserRound size={38}/><h1>{verifyMode?"Verify your account":mode==="register"||mode==="phone-signup"?"Create your account":mode==="forgot"?"Reset your password":"Welcome back"}</h1><p>Secure access to contests, events, businesses, payments and winnings.</p></div>
    {!verifyMode&&mode!=="forgot"&&mode!=="phone"&&mode!=="phone-signup"&&<div className="auth-tabs"><button className={mode==="login"?"active":""} onClick={()=>setMode("login")}>Login</button><button className={mode==="register"?"active":""} onClick={()=>setMode("register")}>Register</button></div>}
    {mode==="login"&&<form onSubmit={passwordLogin}>{authConfig.email_password_enabled&&<><div className="field"><label>Email address</label><div className="input-icon"><Mail/><input type="email" required value={email} onChange={e=>setEmail(e.target.value)} placeholder="name@example.com"/></div></div><div className="field"><label>Password</label><div className="input-icon"><KeyRound/><input type="password" required value={password} onChange={e=>setPassword(e.target.value)} placeholder="Your password"/></div></div><button className="btn btn-primary auth-main" disabled={busy}>Login</button><button type="button" className="text-button" onClick={()=>setMode("forgot")}>Forgot password?</button></>}{(authConfig.email_otp_enabled||authConfig.sms_login_enabled)&&<div className="auth-divider"><span>or</span></div>}{authConfig.email_otp_enabled&&<button type="button" className="btn outline-btn" onClick={sendEmailLoginOtp}>Login with Email OTP</button>}{authConfig.sms_login_enabled&&<button type="button" className="btn outline-btn" onClick={()=>setMode("phone")}><Phone size={15}/> Login with Phone OTP</button>}</form>}
    {mode==="register"&&<div><div className="field"><label>Full name</label><input value={name} onChange={e=>setName(e.target.value)} placeholder="Your full name"/></div><div className="field"><label>Email address</label><input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="name@example.com"/></div><div className="field"><label>Mobile number</label><input value={phone} onChange={e=>setPhone(e.target.value)} placeholder="+91 98XXXXXXXX"/></div><div className="field"><label>Create password</label><input type="password" minLength={8} value={password} onChange={e=>setPassword(e.target.value)} placeholder="Minimum 8 characters"/></div><button className="btn btn-primary auth-main" disabled={busy} onClick={sendRegistrationOtp}>{authConfig.require_email_verification?"Send Email Verification OTP":"Create Account"}</button>{authConfig.sms_signup_enabled&&<><div className="auth-divider"><span>or</span></div><button className="btn outline-btn" onClick={()=>setMode("phone-signup")}><Phone size={15}/> Register with Phone OTP</button></>}<p className="auth-help">{authConfig.require_email_verification?"Your email must be verified before the account is activated.":"Your account will be created immediately after signup."}</p></div>}
    {mode==="phone"&&<div><div className="field"><label>Mobile number</label><div className="input-icon"><Phone/><input value={phone} onChange={e=>setPhone(e.target.value)} placeholder="+91 98XXXXXXXX"/></div></div><button className="btn btn-primary auth-main" disabled={busy} onClick={sendPhoneOtp}>Send Phone OTP</button><button className="text-button" onClick={()=>setMode("login")}>Back to login</button></div>}
    {mode==="phone-signup"&&<div><div className="field"><label>Full name</label><input value={name} onChange={e=>setName(e.target.value)} placeholder="Your full name"/></div><div className="field"><label>Mobile number</label><div className="input-icon"><Phone/><input value={phone} onChange={e=>setPhone(e.target.value)} placeholder="+91 98XXXXXXXX"/></div></div><div className="field"><label>Email address (optional)</label><input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="name@example.com"/></div><div className="field"><label>Create password (optional)</label><input type="password" minLength={8} value={password} onChange={e=>setPassword(e.target.value)} placeholder="Minimum 8 characters"/></div><button className="btn btn-primary auth-main" disabled={busy} onClick={sendPhoneSignupOtp}>Send Registration OTP</button><button className="text-button" onClick={()=>setMode("register")}>Back to email registration</button></div>}
    {verifyMode&&<div><div className="otp-icon"><ShieldCheck size={28}/></div><p className="otp-target">Code sent to <strong>{mode==="verify-phone"||mode==="verify-phone-signup"?phone:email}</strong></p><div className="field"><label>6-digit OTP</label><input className="otp-input" inputMode="numeric" maxLength={6} value={otp} onChange={e=>setOtp(e.target.value.replace(/\D/g,""))} placeholder="000000"/></div><button className="btn btn-primary auth-main" disabled={busy||otp.length<6} onClick={mode==="verify-phone"||mode==="verify-phone-signup"?verifyPhoneOtp:verifyEmailOtp}>Verify OTP</button><button className="text-button" onClick={()=>setMode("login")}>Use another login method</button></div>}
    {mode==="forgot"&&<div><div className="field"><label>Registered email</label><input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="name@example.com"/></div><button className="btn btn-primary auth-main" disabled={busy} onClick={forgot}>Send Reset Link</button><button className="text-button" onClick={()=>setMode("login")}>Back to login</button></div>}
    {message&&<div className="auth-message">{message}</div>}
  </section></div>;
}
