"use client";
import Link from "next/link";
import { FormEvent, useEffect, useMemo, useState } from "react";
import { ChevronLeft, Eye, FilePlus2, Pencil, Save, Trash2 } from "lucide-react";
import { supabase } from "@/lib/supabase";
import { BrandIcon } from "@/components/BrandLogo";

const blank={title:"",slug:"",page_type:"legal",excerpt:"",content:"",meta_title:"",meta_description:"",is_published:false,show_in_footer:true,footer_group:"Legal",sort_order:0};
const slugify=(s:string)=>s.toLowerCase().trim().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"");
export default function PagesManager(){
 const [checking,setChecking]=useState(true),[admin,setAdmin]=useState(false),[rows,setRows]=useState<any[]>([]),[selected,setSelected]=useState<any|null>(null),[form,setForm]=useState<any>(blank),[message,setMessage]=useState("");
 useEffect(()=>{(async()=>{const {data:{user}}=await supabase.auth.getUser();if(!user){setChecking(false);return}const {data:r}=await supabase.from("user_roles").select("role").eq("user_id",user.id).eq("role","admin").maybeSingle();setAdmin(!!r);setChecking(false);if(r)load()})()},[]);
 async function load(){const {data}=await supabase.from("site_pages").select("*").order("footer_group").order("sort_order");setRows(data||[])}
 function edit(r:any|null){setSelected(r);setForm(r?{...r}:blank)}
 async function save(e:FormEvent){e.preventDefault();const payload={...form,slug:form.slug||slugify(form.title),updated_at:new Date().toISOString()};if(selected){const {error}=await supabase.from("site_pages").update(payload).eq("id",selected.id);setMessage(error?.message||"Page updated.")}else{const {error}=await supabase.from("site_pages").insert(payload);setMessage(error?.message||"Page created.")}edit(null);load()}
 async function remove(r:any){if(!confirm(`Delete page “${r.title}”?`))return;const {error}=await supabase.from("site_pages").delete().eq("id",r.id);setMessage(error?.message||"Page deleted.");if(selected?.id===r.id)edit(null);load()}
 const grouped=useMemo(()=>rows.reduce((a:any,r:any)=>{const k=r.footer_group||"Other";(a[k]||=[]).push(r);return a},{}),[rows]);
 if(checking)return <div className="admin-auth-cover"><div className="ma-loader"><BrandIcon size={120}/><strong>Loading Pages</strong><span><i/></span></div></div>;
 if(!admin)return <div className="admin-auth-cover"><div className="admin-auth-card"><h1>Admin access required</h1><Link href="/admin">Return to Admin</Link></div></div>;
 return <div className="pages-manager"><header className="admin-section-header"><div><Link href="/admin" className="back-link"><ChevronLeft size={16}/> Admin</Link><h1>Pages & Policies</h1><p>Create, edit, publish and place legal/policy pages in the public footer.</p></div><button className="admin-primary" onClick={()=>edit(null)}><FilePlus2 size={16}/> New Page</button></header>
 <div className="pages-layout"><aside className="pages-list">{Object.entries(grouped).map(([group,items]:any)=><section key={group}><h3>{group}</h3>{items.map((r:any)=><button key={r.id} className={selected?.id===r.id?"active":""} onClick={()=>edit(r)}><span><strong>{r.title}</strong><small>/{r.slug} • {r.is_published?"Published":"Draft"}</small></span><Pencil size={14}/></button>)}</section>)}</aside>
 <main><form className="page-editor" onSubmit={save}><div className="page-editor-head"><div><h2>{selected?"Edit Page":"Create Page"}</h2><p>Changes publish to <code>/pages/{form.slug||"your-page"}</code>.</p></div>{selected?.is_published&&<Link className="admin-secondary" target="_blank" href={`/pages/${selected.slug}`}><Eye size={15}/> Preview</Link>}</div>
 <div className="editor-grid"><label>Title<input value={form.title||""} onChange={e=>setForm({...form,title:e.target.value})}/></label><label>Slug<input value={form.slug||""} placeholder="auto-generated-from-title" onChange={e=>setForm({...form,slug:e.target.value})}/></label><label>Page type<select value={form.page_type||"legal"} onChange={e=>setForm({...form,page_type:e.target.value})}><option value="legal">Legal</option><option value="policy">Policy</option><option value="general">General</option><option value="help">Help</option></select></label><label>Footer group<input value={form.footer_group||""} onChange={e=>setForm({...form,footer_group:e.target.value})}/></label><label className="span-2">Excerpt<textarea rows={3} value={form.excerpt||""} onChange={e=>setForm({...form,excerpt:e.target.value})}/></label><label className="span-2">Page content<textarea rows={18} value={form.content||""} onChange={e=>setForm({...form,content:e.target.value})}/></label><label>Meta title<input value={form.meta_title||""} onChange={e=>setForm({...form,meta_title:e.target.value})}/></label><label>Sort order<input type="number" value={form.sort_order??0} onChange={e=>setForm({...form,sort_order:Number(e.target.value)})}/></label><label className="span-2">Meta description<textarea rows={3} value={form.meta_description||""} onChange={e=>setForm({...form,meta_description:e.target.value})}/></label></div>
 <div className="page-toggles"><label><input type="checkbox" checked={!!form.is_published} onChange={e=>setForm({...form,is_published:e.target.checked})}/> Published</label><label><input type="checkbox" checked={!!form.show_in_footer} onChange={e=>setForm({...form,show_in_footer:e.target.checked})}/> Show in footer</label></div><div className="page-editor-actions"><button className="admin-primary" type="submit"><Save size={16}/> Save Page</button>{selected&&<button type="button" className="danger-button" onClick={()=>remove(selected)}><Trash2 size={15}/> Delete Page</button>}</div>{message&&<p className="admin-message">{message}</p>}</form></main></div></div>
}
