"use client";
import Link from "next/link";
import { useEffect,useMemo,useState } from "react";
import { ArrowLeft,BriefcaseBusiness,CalendarHeart,CreditCard,LifeBuoy,Search,ShieldCheck,Trophy,UserRound,UsersRound,X } from "lucide-react";
import { supabase } from "@/lib/supabase";
import { BrandIcon } from "@/components/BrandLogo";

const STAFF_ROLES=["admin","moderator","verification","support","finance","content_manager"];
export default function AdminUsersPage(){
 const [user,setUser]=useState<any>(null),[allowed,setAllowed]=useState(false),[loading,setLoading]=useState(true),[profiles,setProfiles]=useState<any[]>([]),[roles,setRoles]=useState<any[]>([]),[activity,setActivity]=useState<Record<string,any>>({}),[q,setQ]=useState(""),[filter,setFilter]=useState("all"),[selected,setSelected]=useState<any>(null),[notice,setNotice]=useState("");
 async function load(){const [p,r,c,e,b,pay,t]=await Promise.all([supabase.from("profiles").select("*").order("created_at",{ascending:false}),supabase.from("user_roles").select("*"),supabase.from("contest_submissions").select("user_id,id"),supabase.from("event_submissions").select("user_id,id"),supabase.from("businesses").select("owner_user_id,id"),supabase.from("payments").select("user_id,id,amount,status"),supabase.from("support_tickets").select("user_id,id,status")]);setProfiles(p.data||[]);setRoles(r.data||[]);const map:any={};const touch=(id:string)=>map[id]??={contests:0,events:0,businesses:0,payments:0,tickets:0,paid:0};(c.data||[]).forEach((x:any)=>{if(x.user_id)touch(x.user_id).contests++});(e.data||[]).forEach((x:any)=>{if(x.user_id)touch(x.user_id).events++});(b.data||[]).forEach((x:any)=>{if(x.owner_user_id)touch(x.owner_user_id).businesses++});(pay.data||[]).forEach((x:any)=>{if(x.user_id){touch(x.user_id).payments++;if(x.status==="paid")touch(x.user_id).paid+=Number(x.amount||0)}});(t.data||[]).forEach((x:any)=>{if(x.user_id)touch(x.user_id).tickets++});setActivity(map)}
 useEffect(()=>{(async()=>{const {data:{user:u}}=await supabase.auth.getUser();setUser(u);if(!u){setLoading(false);return}const {data:r}=await supabase.from("user_roles").select("role").eq("user_id",u.id).eq("role","admin").maybeSingle();if(!r){setLoading(false);return}setAllowed(true);await load();setLoading(false)})()},[]);
 const roleMap=useMemo(()=>roles.reduce((a:any,r:any)=>{(a[r.user_id]??=[]).push(r.role);return a},{}),[roles]);
 const siteUsers=profiles.filter(p=>!(roleMap[p.id]||[]).some((r:string)=>STAFF_ROLES.includes(r)));
 const visible=siteUsers.filter(p=>{const rs=roleMap[p.id]||[];const text=`${p.full_name||""} ${p.email||""} ${p.mobile||""} ${p.city||""}`.toLowerCase();return (!q||text.includes(q.toLowerCase()))&&(filter==="all"||filter==="business"&&rs.includes("business")||filter==="member"&&!rs.includes("business"))});
 async function setBusiness(id:string,on:boolean){if(on)await supabase.from("user_roles").upsert({user_id:id,role:"business"});else await supabase.from("user_roles").delete().eq("user_id",id).eq("role","business");await load();setNotice(on?"Business owner access enabled.":"Business owner access removed.")}
 if(loading)return <div className="ma-loader"><BrandIcon size={110}/><strong>Loading Site Users</strong></div>;
 if(!user||!allowed)return <div className="admin-auth-cover"><div className="admin-auth-card"><BrandIcon size={80}/><h1>Restricted</h1><p>Administrator access required.</p><Link className="admin-primary" href="/admin">Admin Login</Link></div></div>;
 return <div className="identity-admin"><header><div><Link href="/admin"><ArrowLeft size={15}/>Back to Admin</Link><h1>Site Users</h1><p>Customer accounts, participants and business owners. Staff accounts are excluded from this workspace.</p></div><Link className="identity-staff-link" href="/admin/staff"><ShieldCheck size={15}/>Staff & Roles</Link></header>
 <div className="identity-stats"><article><UsersRound/><span>Site users</span><strong>{siteUsers.length}</strong></article><article><UserRound/><span>Members</span><strong>{siteUsers.filter(p=>!(roleMap[p.id]||[]).includes("business")).length}</strong></article><article><BriefcaseBusiness/><span>Business owners</span><strong>{siteUsers.filter(p=>(roleMap[p.id]||[]).includes("business")).length}</strong></article></div>
 <main><div className="identity-toolbar"><div className="identity-search"><Search size={16}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search name, email, phone or city…"/></div><div className="identity-tabs">{[["all","All Users"],["member","Members"],["business","Business Owners"]].map(([k,l])=><button className={filter===k?"active":""} key={k} onClick={()=>setFilter(k)}>{l}</button>)}</div></div>
 <div className="identity-table"><div className="identity-row identity-head"><span>User</span><span>Contact</span><span>Account type</span><span>Activity</span><span>Actions</span></div>{visible.map(p=>{const rs=roleMap[p.id]||[];const business=rs.includes("business");const a=activity[p.id]||{};return <div className="identity-row" key={p.id}><div><strong>{p.full_name||"Unnamed User"}</strong><small>{[p.city,p.state].filter(Boolean).join(", ")||"Location not set"}</small></div><div><span>{p.email||"No email"}</span><small>{p.mobile||"No phone"}</small></div><div><em className={business?"identity-badge business":"identity-badge"}>{business?"Business Owner":"Member"}</em></div><div><span>{(a.contests||0)+(a.events||0)+(a.businesses||0)} platform records</span><small>{a.tickets||0} support tickets</small></div><div className="identity-action-stack"><button onClick={()=>setSelected({...p,business,...a})}>View User</button><button onClick={()=>setBusiness(p.id,!business)}>{business?"Remove Business":"Make Business"}</button></div></div>})}{!visible.length&&<div className="identity-empty">No matching site users.</div>}</div></main>
 {selected&&<div className="staff-modal-bg" onClick={()=>setSelected(null)}><section className="staff-modal user-detail-modal" onClick={e=>e.stopPropagation()}><header><div><span>USER PROFILE</span><h2>{selected.full_name||"Site User"}</h2><p>{selected.email||selected.mobile}</p></div><button onClick={()=>setSelected(null)}><X size={18}/></button></header><div className="user-detail-body"><div className="user-detail-profile"><UserRound/><div><strong>{selected.full_name||"Unnamed user"}</strong><span>{selected.email||"No email"}</span><span>{selected.mobile||"No phone"}</span><small>{[selected.address,selected.city,selected.state,selected.pincode].filter(Boolean).join(", ")||"Address not provided"}</small></div></div><div className="user-activity-grid"><article><Trophy/><span>Contest entries</span><strong>{selected.contests||0}</strong></article><article><CalendarHeart/><span>Event requests</span><strong>{selected.events||0}</strong></article><article><BriefcaseBusiness/><span>Businesses</span><strong>{selected.businesses||0}</strong></article><article><CreditCard/><span>Payments</span><strong>{selected.payments||0}</strong></article><article><LifeBuoy/><span>Support tickets</span><strong>{selected.tickets||0}</strong></article><article><CreditCard/><span>Paid value</span><strong>₹{Number(selected.paid||0).toLocaleString("en-IN")}</strong></article></div><div className="user-detail-actions"><Link href={`/support`} target="_blank">Open Support Center</Link><button onClick={()=>setBusiness(selected.id,!selected.business)}>{selected.business?"Remove Business Owner Role":"Enable Business Owner Role"}</button></div></div></section></div>}{notice&&<div className="ma-toast">{notice}</div>}</div>;
}
