"use client";
import {useEffect,useMemo,useState} from "react";
import Link from "next/link";
import {BarChart3,CalendarDays,CheckCircle2,Clock3,ExternalLink,Facebook,Instagram,Linkedin,Plus,RefreshCw,Send,Settings2,Share2,Video,Youtube} from "lucide-react";
import {supabase} from "@/lib/supabase";
import "./social.css";

type Tab="overview"|"calendar"|"queue"|"channels"|"analytics";
const providerIcon=(p:string)=>p==="youtube"?Youtube:p==="facebook"?Facebook:p==="instagram"?Instagram:p==="linkedin"?Linkedin:Share2;
const nice=(v:any)=>v?new Date(v).toLocaleString("en-IN",{dateStyle:"medium",timeStyle:"short"}):"—";
const providerLabel=(p:string)=>({youtube:"YouTube",facebook:"Facebook",instagram:"Instagram",x:"X",linkedin:"LinkedIn",threads:"Threads"} as any)[p]||p;

export default function SocialPublishingPage(){
 const [tab,setTab]=useState<Tab>("overview"),[loading,setLoading]=useState(true),[accounts,setAccounts]=useState<any[]>([]),[posts,setPosts]=useState<any[]>([]),[destinations,setDestinations]=useState<any[]>([]),[sources,setSources]=useState<any[]>([]),[composer,setComposer]=useState(false),[sourceType,setSourceType]=useState("contest_submission"),[sourceId,setSourceId]=useState(""),[caption,setCaption]=useState(""),[scheduledAt,setScheduledAt]=useState(""),[providers,setProviders]=useState<string[]>([]),[message,setMessage]=useState("");
 async function load(){setLoading(true);const [{data:a},{data:p},{data:d},{data:c},{data:e},{data:b}]=await Promise.all([
  supabase.from("social_accounts").select("*").order("provider"),
  supabase.from("social_posts").select("*").order("created_at",{ascending:false}),
  supabase.from("social_post_destinations").select("*").order("created_at",{ascending:false}),
  supabase.from("contest_submissions").select("id,status,video_url,title,participant_name,created_at,contests(title)").in("status",["approved","shortlisted","finalist","winner"]),
  supabase.from("event_submissions").select("id,status,video_url,title,name,event_date,created_at,event_categories(name)").in("status",["approved","scheduled","published"]),
  supabase.from("businesses").select("id,name,slug,status,description,logo_url,photos,city,state").eq("status","approved")
 ]);setAccounts(a||[]);setPosts(p||[]);setDestinations(d||[]);setSources([...(c||[]).map((x:any)=>({...x,_type:"contest_submission",_label:x.title||x.participant_name||x.contests?.title||"Contest submission"})),...(e||[]).map((x:any)=>({...x,_type:"event_submission",_label:x.title||x.name||x.event_categories?.name||"Event submission"})),...(b||[]).map((x:any)=>({...x,_type:"business",_label:x.name}))]);setLoading(false)}
 useEffect(()=>{load()},[]);
 const filteredSources=useMemo(()=>sources.filter(s=>s._type===sourceType),[sources,sourceType]);
 const scheduled=posts.filter(p=>p.status==="scheduled").length,published=posts.filter(p=>p.status==="published").length,failed=posts.filter(p=>p.status==="failed"||p.status==="partial").length,connected=accounts.filter(a=>a.status==="connected").length;
 const destinationMap=useMemo(()=>destinations.reduce((m:any,d:any)=>{(m[d.social_post_id]||=[]).push(d);return m},{}),[destinations]);
 async function createPost(publishNow=false){if(!sourceId||!caption||!providers.length){setMessage("Choose content, write a caption and select at least one channel.");return}const src=sources.find(s=>s.id===sourceId);const media=src?.video_url||src?.logo_url||src?.photos?.[0]||null;const link=sourceType==="business"?`https://app.srigaurnitai.com/businesses/${src?.slug}`:null;const {data:{user}}=await supabase.auth.getUser();const when=publishNow?null:(scheduledAt?new Date(scheduledAt).toISOString():null);const status=publishNow?"publishing":when?"scheduled":"draft";const {data:post,error}=await supabase.from("social_posts").insert({source_type:sourceType,source_id:sourceId,title:src?._label,caption,media_url:media,link_url:link,status,scheduled_at:when,created_by:user?.id}).select().single();if(error||!post){setMessage(error?.message||"Could not create post");return}const rows=providers.map(provider=>({social_post_id:post.id,provider,social_account_id:accounts.find(a=>a.provider===provider)?.id||null,status:"queued"}));await supabase.from("social_post_destinations").insert(rows);setMessage(publishNow?"Added to publishing queue. Connect provider APIs before dispatch.":when?"Post scheduled.":"Draft saved.");setComposer(false);setCaption("");setSourceId("");setProviders([]);setScheduledAt("");load()}
 const monthDays=useMemo(()=>{const now=new Date();const start=new Date(now.getFullYear(),now.getMonth(),1);const first=start.getDay();const days=new Date(now.getFullYear(),now.getMonth()+1,0).getDate();return Array.from({length:first+days},(_,i)=>i<first?null:i-first+1)},[]);
 return <main className="social-hub">
  <header className="social-hero"><div><span>CONTENT DISTRIBUTION</span><h1>Social Publishing Hub</h1><p>Turn approved community content into scheduled campaigns across Sri Gaur Nitai social channels.</p></div><div className="social-hero-actions"><button onClick={load}><RefreshCw size={16}/>Refresh</button><button className="primary" onClick={()=>setComposer(true)}><Plus size={16}/>Create Post</button></div></header>
  <section className="social-kpis"><article><Share2/><span>Connected channels</span><strong>{connected}/{accounts.length}</strong></article><article><CalendarDays/><span>Scheduled</span><strong>{scheduled}</strong></article><article><CheckCircle2/><span>Published</span><strong>{published}</strong></article><article><Clock3/><span>Needs attention</span><strong>{failed}</strong></article></section>
  <nav className="social-tabs">{[["overview","Overview"],["calendar","Calendar"],["queue","Publishing Queue"],["channels","Channels"],["analytics","Analytics"]].map(([k,l])=><button key={k} className={tab===k?"active":""} onClick={()=>setTab(k as Tab)}>{l}</button>)}</nav>
  {loading?<div className="social-loading">Loading publishing workspace…</div>:<>
   {tab==="overview"&&<div className="social-overview-grid"><section className="social-panel"><div className="panel-head"><div><h2>Upcoming publishing</h2><p>Scheduled and queued social posts.</p></div><button onClick={()=>setComposer(true)}><Plus size={14}/>New</button></div><div className="post-list">{posts.filter(p=>["scheduled","publishing","draft"].includes(p.status)).slice(0,6).map(p=><article key={p.id}><div className="post-thumb">{p.media_url?<img src={p.media_url} alt=""/>:<Share2/>}</div><div><strong>{p.title||"Social post"}</strong><p>{p.caption}</p><small>{p.status==="scheduled"?nice(p.scheduled_at):p.status}</small></div><div className="channel-dots">{(destinationMap[p.id]||[]).map((d:any)=>{const I=providerIcon(d.provider);return <span key={d.id} title={providerLabel(d.provider)}><I size={14}/></span>})}</div></article>)}{!posts.length&&<div className="empty">No social posts yet. Create your first campaign.</div>}</div></section><section className="social-panel compact"><div className="panel-head"><div><h2>Approved content pool</h2><p>Ready to promote.</p></div></div><div className="source-count"><div><Video/><span>Contest entries</span><strong>{sources.filter(s=>s._type==="contest_submission").length}</strong></div><div><CalendarDays/><span>Event submissions</span><strong>{sources.filter(s=>s._type==="event_submission").length}</strong></div><div><Share2/><span>Businesses</span><strong>{sources.filter(s=>s._type==="business").length}</strong></div></div><button className="full" onClick={()=>setComposer(true)}>Create from approved content</button></section></div>}
   {tab==="calendar"&&<section className="social-panel calendar-panel"><div className="panel-head"><div><h2>{new Date().toLocaleString("en-IN",{month:"long",year:"numeric"})}</h2><p>Calendar view of scheduled and published activity.</p></div></div><div className="calendar-grid">{["Sun","Mon","Tue","Wed","Thu","Fri","Sat"].map(d=><b key={d}>{d}</b>)}{monthDays.map((d,i)=><div key={i} className={!d?"blank":""}>{d&&<><span>{d}</span>{posts.filter(p=>{const dt=p.scheduled_at||p.published_at;return dt&&new Date(dt).getDate()===d&&new Date(dt).getMonth()===new Date().getMonth()}).slice(0,3).map(p=><small key={p.id}>{p.title||"Post"}</small>)}</>}</div>)}</div></section>}
   {tab==="queue"&&<section className="social-panel"><div className="panel-head"><div><h2>Publishing Queue</h2><p>Every destination and delivery state in one place.</p></div></div><div className="queue-table"><div className="q-head"><span>Content</span><span>Channels</span><span>Schedule</span><span>Status</span></div>{posts.map(p=><div className="q-row" key={p.id}><div><strong>{p.title||"Post"}</strong><small>{p.caption}</small></div><div className="channel-dots">{(destinationMap[p.id]||[]).map((d:any)=>{const I=providerIcon(d.provider);return <span key={d.id}><I size={15}/></span>})}</div><span>{nice(p.scheduled_at||p.published_at||p.created_at)}</span><em className={`pstatus ${p.status}`}>{p.status}</em></div>)}</div></section>}
   {tab==="channels"&&<section className="channel-grid">{accounts.map(a=>{const I=providerIcon(a.provider);return <article key={a.id}><div className="channel-icon"><I/></div><div><h3>{providerLabel(a.provider)}</h3><p>{a.page_name||a.account_name||"Sri Gaur Nitai account"}</p><span className={`connection ${a.status}`}>{a.status}</span></div><Link href="/admin/integrations"><Settings2 size={14}/>{a.status==="connected"?"Manage":"Connect"}</Link></article>})}<div className="channel-note"><strong>Secure connection model</strong><p>OAuth tokens and provider secrets should be stored server-side through Integrations/Edge Functions, not exposed in the browser or database UI.</p></div></section>}
   {tab==="analytics"&&<section className="social-panel analytics-empty"><BarChart3/><h2>Cross-channel performance</h2><p>Views, reach, likes, comments, shares, clicks and watch time will aggregate here after provider API connections are active.</p></section>}
  </>}
  {composer&&<div className="social-modal-backdrop"><section className="social-composer"><header><div><span>NEW SOCIAL CAMPAIGN</span><h2>Publish approved content</h2></div><button onClick={()=>setComposer(false)}>×</button></header><label>Content type<select value={sourceType} onChange={e=>{setSourceType(e.target.value);setSourceId("")}}><option value="contest_submission">Contest submission</option><option value="event_submission">Event submission</option><option value="business">Business promotion</option></select></label><label>Approved content<select value={sourceId} onChange={e=>setSourceId(e.target.value)}><option value="">Select content…</option>{filteredSources.map(s=><option key={s.id} value={s.id}>{s._label}</option>)}</select></label><label>Caption<textarea rows={5} value={caption} onChange={e=>setCaption(e.target.value)} placeholder="Write the social caption, hashtags, CTA and credits…"/></label><div className="composer-channels"><span>Publish to</span>{accounts.map(a=>{const I=providerIcon(a.provider);const active=providers.includes(a.provider);return <button type="button" key={a.id} className={active?"active":""} onClick={()=>setProviders(v=>active?v.filter(x=>x!==a.provider):[...v,a.provider])}><I size={16}/>{providerLabel(a.provider)}<small>{a.status}</small></button>})}</div><label>Schedule date & time<input type="datetime-local" value={scheduledAt} onChange={e=>setScheduledAt(e.target.value)}/></label><footer><button onClick={()=>setComposer(false)}>Cancel</button><button onClick={()=>createPost(false)}><Clock3 size={15}/>Save / Schedule</button><button className="primary" onClick={()=>createPost(true)}><Send size={15}/>Publish Now</button></footer></section></div>}
  {message&&<div className="social-toast">{message}<button onClick={()=>setMessage("")}>×</button></div>}
 </main>
}
