import Link from "next/link";
import { CalendarDays, IndianRupee, Trophy } from "lucide-react";
import { supabase } from "@/lib/supabase";

export default async function ContestsPage({searchParams}:{searchParams:Promise<{category?:string;view?:string}>}){
 const {category,view}=await searchParams;
 let q=supabase.from("contests").select("id,title,slug,description,submission_close_at,participation_fee,first_prize,second_prize,third_prize,is_featured,contest_categories(name,slug)").eq("is_active",true).order("is_featured",{ascending:false}).order("submission_close_at");
 const {data:rows}=await q; const contests=(rows||[]).filter((c:any)=>!category||c.contest_categories?.slug===category);
 const {data:recent}=await supabase.from("contest_submissions").select("id,reference_code,title,status,submitted_at,profiles:user_id(full_name),contests(title)").in("status",["approved","shortlisted","winner"]).order("submitted_at",{ascending:false}).limit(5);
 return <div className="page">
  <div className="page-title"><div><h1>Contests</h1><p>Show your devotion. Inspire the community.</p></div></div>
  <div className="segmented"><Link className={!view?"active":""} href="/contests">Ongoing</Link><Link className={view==="upcoming"?"active":""} href="/contests?view=upcoming">Upcoming</Link><Link href="/account#contests">My Submissions</Link></div>
  <section className="hero-banner"><div className="hero-copy"><h2>🏆 <span className="gold">Show Your Devotion.</span><br/>Inspire the World.</h2><p>Open a contest to view rules, eligibility, prizes and submit your video.</p><Link className="hero-cta" href="/videos">Watch Public Videos</Link></div></section>
  <section className="section">{contests.map((c:any)=>{const closes=c.submission_close_at?new Date(c.submission_close_at).toLocaleDateString("en-IN",{day:"numeric",month:"short",year:"numeric"}):"Open";return <Link className="contest-card" href={`/contests/${c.slug}`} key={c.id}><div className="contest-art">{c.contest_categories?.name?.includes("Singing")?"🎙️":c.contest_categories?.name?.includes("Kids")?"🪈":"🏆"}</div><div className="contest-info"><h3>{c.title}</h3><p>{c.contest_categories?.name}</p><div className="meta-line"><span><CalendarDays size={12}/>Deadline: {closes}</span><span><IndianRupee size={12}/>Entry: {Number(c.participation_fee)?`₹${Number(c.participation_fee).toLocaleString("en-IN")}`:"Free"}</span></div><div className="prize-row"><strong><Trophy size={12}/> First Prize ₹{Number(c.first_prize||0).toLocaleString("en-IN")}</strong><span className="btn btn-primary">View & Participate</span></div></div></Link>})}</section>
  <section className="section"><div className="section-head"><div><h2>Public Participant Highlights</h2><p>Approved and shortlisted community entries.</p></div><Link className="section-link" href="/videos?type=contest">Watch videos</Link></div><div className="request-list">{(recent||[]).map((s:any)=><Link href="/videos?type=contest" className="request-row" key={s.id}><div className="request-thumb" style={{background:'linear-gradient(145deg,#f6d8be,#fff1df)',display:'grid',placeItems:'center',fontSize:28}}>👤</div><div><h3>{s.profiles?.full_name||s.title}</h3><p>{s.contests?.title} • {s.reference_code}</p><p>Submitted {new Date(s.submitted_at).toLocaleDateString("en-IN")}</p></div><span className={`status ${s.status==="approved"?"approved":"shortlisted"}`}>{String(s.status).replaceAll("_"," ")}</span></Link>)}</div></section>
 </div>;
}
