import Link from "next/link";
import { CalendarDays, ChevronRight, IndianRupee, Play, Sparkles, Trophy } from "lucide-react";
import { supabase } from "@/lib/supabase";

const fallback:Record<string,string>={Singing:"https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?auto=format&fit=crop&w=1000&q=82",Dancing:"https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?auto=format&fit=crop&w=1000&q=82","Kids Content":"https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?auto=format&fit=crop&w=1000&q=82","Short Films":"https://images.unsplash.com/photo-1485846234645-a62644f84728?auto=format&fit=crop&w=1000&q=82","Educational Content":"https://images.unsplash.com/photo-1524995997946-a1c2e315a42f?auto=format&fit=crop&w=1000&q=82"};
const categoryOf=(c:any)=>Array.isArray(c?.contest_categories)?c.contest_categories[0]:c?.contest_categories;
export default async function ContestsPage({searchParams}:{searchParams:Promise<{category?:string;view?:string}>}){const {category,view}=await searchParams;const [{data:rows},{data:recent},{data:cats}]=await Promise.all([
 supabase.from("contests").select("id,title,slug,subtitle,description,banner_url,card_badge,cta_label,theme_start,theme_end,submission_close_at,participation_fee,first_prize,second_prize,third_prize,is_featured,public_order,contest_categories(name,slug)").eq("is_active",true).order("public_order").order("is_featured",{ascending:false}),
 supabase.from("public_videos").select("id,title,participant_name,thumbnail_url,contest_id,published_at").eq("content_type","contest").eq("status","published").order("published_at",{ascending:false}).limit(6),
 supabase.from("contest_categories").select("id,name,slug").eq("is_active",true).order("sort_order")]);
 const contests=((rows||[]) as any[]).filter((c:any)=>!category||categoryOf(c)?.slug===category);const featured=contests.find((c:any)=>c.is_featured)||contests[0];const fc=categoryOf(featured);const fimg=featured?.banner_url||fallback[fc?.name]||fallback.Singing;
 return <div className="page contests-page"><div className="page-title-row contest-page-head"><div><h1>Contests</h1><p>Join contests, submit videos and track your results.</p></div><Link className="btn btn-primary compact-action" href="/videos?type=contest"><Play size={14}/><span>Videos</span></Link></div><nav className="segmented contest-segments"><Link className={!view?"active":""} href="/contests">Ongoing</Link><Link className={view==="upcoming"?"active":""} href="/contests?view=upcoming">Upcoming</Link><Link href="/account#contests">My Submissions</Link></nav><div className="category-row contest-category-scroll" style={{marginBottom:12}}><Link className={!category?"category-chip active":"category-chip"} href="/contests">All</Link>{(cats||[]).map((c:any)=><Link key={c.id} className={category===c.slug?"category-chip active":"category-chip"} href={`/contests?category=${c.slug}`}>{c.name}</Link>)}</div>
 {featured&&<Link className="featured-business-hero contest-featured" href={`/contests/${featured.slug}`} style={{backgroundImage:`linear-gradient(90deg,${featured.theme_start||'#470420'}f7,${featured.theme_end||'#7b173c'}99,rgba(71,4,32,.08)),url(${fimg})`}}><div><span className="gold-badge"><Sparkles size={13}/>{featured.card_badge||"Featured Contest"}</span><h2>{featured.title}</h2>{featured.subtitle&&<h3 style={{color:'#ffd15c'}}>{featured.subtitle}</h3>}<p>{featured.description}</p><div className="profile-meta-strip"><span><CalendarDays size={13}/>Closes {featured.submission_close_at?new Date(featured.submission_close_at).toLocaleDateString("en-IN",{day:"numeric",month:"short"}):"Open"}</span><span><IndianRupee size={13}/>{Number(featured.participation_fee)?`₹${Number(featured.participation_fee).toLocaleString("en-IN")}`:"Free entry"}</span><span><Trophy size={13}/>₹{Number(featured.first_prize||0).toLocaleString("en-IN")} first prize</span></div><span className="btn gold-btn">{featured.cta_label||"View & Participate"} <ChevronRight size={15}/></span></div></Link>}
 <section className="section"><div className="section-head"><div><h2>Active Contests</h2><p>Open a contest for rules, prizes and public entries.</p></div></div><div className="business-grid contest-card-grid">{contests.map((c:any)=>{const cat=categoryOf(c);const closes=c.submission_close_at?new Date(c.submission_close_at).toLocaleDateString("en-IN",{day:"numeric",month:"short",year:"numeric"}):"Open";const img=c.banner_url||fallback[cat?.name]||fallback.Singing;return <Link className="business-card contest-list-card" href={`/contests/${c.slug}`} key={c.id}><div className="business-thumb" style={{backgroundImage:`url(${img})`}}>{(c.is_featured||c.card_badge)&&<span>{c.card_badge||"Featured"}</span>}</div><div className="business-card-copy"><div className="business-rating"><Trophy size={13}/> ₹{Number(c.first_prize||0).toLocaleString("en-IN")}</div><h3>{c.title}</h3><p>{c.subtitle||cat?.name||"Contest"}</p><span className="business-location"><CalendarDays size={13}/>{closes}</span><div className="service-mini"><em>{Number(c.participation_fee)?`Entry ₹${Number(c.participation_fee).toLocaleString("en-IN")}`:"Free Entry"}</em><em>Video Contest</em></div><span className="btn btn-outline contest-card-cta">{c.cta_label||"View Contest"}</span></div></Link>})}</div></section>
 <section className="section"><div className="section-head"><div><h2>Recent Community Entries</h2><p>Approved videos are visible publicly.</p></div><Link className="section-link" href="/videos?type=contest">View all</Link></div><div className="video-grid">{(recent||[]).map((v:any)=><Link href={`/videos/${v.id}`} className="video-card" key={v.id}><div className="video-thumb" style={{backgroundImage:`url(${v.thumbnail_url||fallback.Singing})`}}><span className="play-orb"><Play size={19} fill="currentColor"/></span></div><div className="video-copy"><span>Public Entry</span><h3>{v.title}</h3><p>by {v.participant_name||"Participant"}</p></div></Link>)}</div></section></div>}
