"use client";
import { FormEvent, useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { CheckCircle2, ChevronLeft, PlugZap, Save, ShieldCheck } from "lucide-react";
import { supabase } from "@/lib/supabase";
import { BrandIcon } from "@/components/BrandLogo";

type Provider={id:string;name:string;description:string;publicFields:{key:string;label:string;type?:string}[];secretFields:{key:string;label:string}[]};
const providers:Provider[]=[
{id:"mux",name:"Mux Video",description:"Direct video uploads, playback assets and public contest/event videos.",publicFields:[{key:"environment_id",label:"Environment ID"},{key:"environment_key",label:"Environment Key"}],secretFields:[{key:"token_id",label:"Access Token ID"},{key:"token_secret",label:"Token Secret"}]},
{id:"razorpay",name:"Razorpay",description:"UPI, cards, netbanking and payment order verification.",publicFields:[{key:"currency",label:"Currency"},{key:"company_name",label:"Checkout company name"}],secretFields:[{key:"key_id",label:"Key ID"},{key:"key_secret",label:"Key Secret"},{key:"webhook_secret",label:"Webhook Secret"}]},
{id:"google_maps",name:"Google Maps",description:"Places search, business locations, address autocomplete and maps.",publicFields:[{key:"browser_api_key",label:"Browser API Key"},{key:"map_id",label:"Map ID"},{key:"country",label:"Default country"}],secretFields:[]},
{id:"youtube",name:"YouTube",description:"Published video metadata and future automated publishing.",publicFields:[{key:"channel_id",label:"Channel ID"}],secretFields:[{key:"client_id",label:"OAuth Client ID"},{key:"client_secret",label:"OAuth Client Secret"},{key:"refresh_token",label:"Refresh Token"}]},
{id:"firebase",name:"Firebase / FCM",description:"Android push notifications and notification delivery.",publicFields:[{key:"project_id",label:"Project ID"},{key:"messaging_sender_id",label:"Messaging Sender ID"},{key:"app_id",label:"App ID"},{key:"vapid_key",label:"Web Push VAPID Key"}],secretFields:[{key:"service_account_json",label:"Service Account JSON"}]},
{id:"smtp",name:"Email / SMTP",description:"Transactional email, OTP delivery and platform notifications.",publicFields:[{key:"host",label:"SMTP Host"},{key:"port",label:"Port"},{key:"from_email",label:"From Email"},{key:"from_name",label:"From Name"}],secretFields:[{key:"username",label:"SMTP Username"},{key:"password",label:"SMTP Password"}]},
{id:"whatsapp",name:"WhatsApp",description:"Support links and future transactional WhatsApp notifications.",publicFields:[{key:"provider",label:"Provider"},{key:"phone_number_id",label:"Phone Number ID"},{key:"support_number",label:"Support Number"}],secretFields:[{key:"access_token",label:"Access Token"}]},
{id:"cashfree",name:"Cashfree",description:"Optional secondary Indian payment gateway.",publicFields:[{key:"environment",label:"Environment"}],secretFields:[{key:"app_id",label:"App ID"},{key:"secret_key",label:"Secret Key"}]}
];

export default function IntegrationManager(){
 const [checking,setChecking]=useState(true),[admin,setAdmin]=useState(false),[active,setActive]=useState("mux"),[message,setMessage]=useState("");
 const [configs,setConfigs]=useState<Record<string,any>>({}),[status,setStatus]=useState<Record<string,string[]>>({}),[form,setForm]=useState<Record<string,any>>({}),[secrets,setSecrets]=useState<Record<string,string>>({});
 const provider=useMemo(()=>providers.find(p=>p.id===active)!,[active]);
 useEffect(()=>{(async()=>{const {data:{user}}=await supabase.auth.getUser();if(!user){setChecking(false);return}const {data:r}=await supabase.from("user_roles").select("role").eq("user_id",user.id).eq("role","admin").maybeSingle();setAdmin(!!r);setChecking(false);if(r)await refresh()})()},[]);
 async function refresh(){const {data,error}=await supabase.functions.invoke("admin-integrations",{body:{action:"status"}});if(error){setMessage(error.message);return}const cm:any={};for(const x of data?.configs||[])cm[x.provider]=x;const sm:any={};for(const x of data?.secret_status||[]){sm[x.provider]=sm[x.provider]||[];sm[x.provider].push(x.secret_key)}setConfigs(cm);setStatus(sm)}
 useEffect(()=>{const c=configs[active]||{};setForm({enabled:!!c.enabled,mode:c.mode||"test",...(c.public_config||{})});setSecrets({})},[active,configs]);
 async function save(e:FormEvent){e.preventDefault();setMessage("Saving securely…");const pub:any={...form};delete pub.enabled;delete pub.mode;const {data,error}=await supabase.functions.invoke("admin-integrations",{body:{action:"save",provider:active,enabled:!!form.enabled,mode:form.mode||"test",config:pub,secrets}});setMessage(error?.message||data?.error||"Integration settings saved.");if(!error&&!data?.error)await refresh()}
 if(checking)return <div className="admin-auth-cover"><div className="ma-loader"><BrandIcon size={120}/><strong>Loading Integrations</strong><span><i/></span></div></div>;
 if(!admin)return <div className="admin-auth-cover"><div className="admin-auth-card"><BrandIcon size={90}/><h1>Admin access required</h1><Link href="/admin">Return to Admin Login</Link></div></div>;
 return <div className="integrations-page"><header className="admin-section-header"><div><Link href="/admin" className="back-link"><ChevronLeft size={16}/> Admin</Link><h1>Integrations</h1><p>Configure payment, video, maps, notifications and external services.</p></div><div className="secure-pill"><ShieldCheck size={15}/> Secrets stored server-side</div></header>
 <div className="integration-layout"><aside className="integration-nav">{providers.map(p=><button className={active===p.id?"active":""} onClick={()=>setActive(p.id)} key={p.id}><PlugZap size={16}/><span><strong>{p.name}</strong><small>{configs[p.id]?.enabled?"Enabled":"Not enabled"}</small></span></button>)}</aside>
 <main className="integration-main"><form onSubmit={save} className="integration-card"><div className="integration-title"><div><h2>{provider.name}</h2><p>{provider.description}</p></div>{configs[active]?.enabled&&<CheckCircle2 size={24}/>}</div><div className="integration-switches"><label><input type="checkbox" checked={!!form.enabled} onChange={e=>setForm({...form,enabled:e.target.checked})}/> Enabled</label><label>Mode<select value={form.mode||"test"} onChange={e=>setForm({...form,mode:e.target.value})}><option value="test">Test</option><option value="production">Production</option></select></label></div>
 <section><h3>Configuration</h3><div className="integration-fields">{provider.publicFields.map(f=><label key={f.key}>{f.label}<input value={form[f.key]||""} onChange={e=>setForm({...form,[f.key]:e.target.value})}/></label>)}</div></section>
 {provider.secretFields.length>0&&<section><h3>Protected credentials</h3><p className="integration-help">Existing secret values are never returned to the browser. Leave a field blank to keep the current value.</p><div className="integration-fields">{provider.secretFields.map(f=><label key={f.key}>{f.label}{status[active]?.includes(f.key)&&<small className="configured-tag">Configured</small>}<input type="password" autoComplete="new-password" value={secrets[f.key]||""} placeholder={status[active]?.includes(f.key)?"•••••••• (configured)":"Enter credential"} onChange={e=>setSecrets({...secrets,[f.key]:e.target.value})}/></label>)}</div></section>}
 {active==="mux"&&<div className="integration-note"><strong>Mux requirement:</strong> Environment ID/Environment Key are not enough for API uploads. Add an Access Token ID and Token Secret from Mux Access Tokens. Once saved, the deployed <code>mux-create-upload</code> backend can issue authenticated direct-upload URLs.</div>}
 {active==="razorpay"&&<div className="integration-note"><strong>Razorpay:</strong> save Key ID + Key Secret, switch to Production only after live keys are issued, and restrict webhook processing to your configured webhook secret.</div>}
 <button className="admin-primary" type="submit"><Save size={16}/> Save {provider.name}</button>{message&&<p className="admin-message">{message}</p>}</form></main></div></div>
}
