"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { ArrowLeft, CheckCircle2, LifeBuoy, MessageSquareText, Send, ShieldAlert } from "lucide-react";
import { supabase } from "@/lib/supabase";
import { BrandIcon } from "@/components/BrandLogo";

type TicketRow={id:string;ticket_number:string;subject:string;message:string;status:string;priority:string;category:string;related_type?:string|null;related_id?:string|null;requester_name?:string|null;requester_email?:string|null;requester_phone?:string|null;assigned_to?:string|null;created_at:string;updated_at:string};

export default function AdminSupportPage(){
 const [user,setUser]=useState<any>(null),[allowed,setAllowed]=useState(false),[loading,setLoading]=useState(true),[tickets,setTickets]=useState<TicketRow[]>([]),[selected,setSelected]=useState<TicketRow|null>(null),[messages,setMessages]=useState<any[]>([]),[profiles,setProfiles]=useState<any[]>([]),[staffIds,setStaffIds]=useState<string[]>([]),[filter,setFilter]=useState("open"),[reply,setReply]=useState(""),[internal,setInternal]=useState(""),[notice,setNotice]=useState("");
 const stats=useMemo(()=>({open:tickets.filter(t=>["open","in_progress","waiting_user"].includes(t.status)).length,urgent:tickets.filter(t=>t.priority==="urgent"&&t.status!=="closed").length,resolved:tickets.filter(t=>t.status==="resolved").length,total:tickets.length}),[tickets]);
 async function boot(){const {data:{user:u}}=await supabase.auth.getUser();setUser(u);if(!u){setLoading(false);return}const {data:roles}=await supabase.from("user_roles").select("role").eq("user_id",u.id);if(!roles?.some((r:any)=>["admin","moderator","support"].includes(r.role))){setLoading(false);return}setAllowed(true);await load();setLoading(false)}
 async function load(){const [t,p,r]=await Promise.all([supabase.from("support_tickets").select("*").order("updated_at",{ascending:false}),supabase.from("profiles").select("id,full_name,email"),supabase.from("user_roles").select("user_id,role").in("role",["admin","moderator","support"])]);setTickets((t.data||[]) as TicketRow[]);setProfiles(p.data||[]);setStaffIds([...(new Set((r.data||[]).map((x:any)=>x.user_id)))] as string[])}
 useEffect(()=>{boot()},[]);
 async function openTicket(t:TicketRow){setSelected(t);const {data}=await supabase.from("support_messages").select("*").eq("ticket_id",t.id).order("created_at");setMessages(data||[])}
 async function patch(p:any){if(!selected)return;const {error}=await supabase.from("support_tickets").update({...p,updated_at:new Date().toISOString()}).eq("id",selected.id);if(error){setNotice(error.message);return}const next={...selected,...p};setSelected(next);await load();setNotice("Ticket updated.")}
 async function send(isInternal=false){const text=(isInternal?internal:reply).trim();if(!selected||!text||!user)return;const {error}=await supabase.from("support_messages").insert({ticket_id:selected.id,sender_user_id:user.id,sender_role:"staff",message:text,is_internal:isInternal});if(error){setNotice(error.message);return}if(isInternal)setInternal("");else setReply("");const nextStatus=isInternal?selected.status:"waiting_user";await supabase.from("support_tickets").update({last_reply_at:new Date().toISOString(),status:nextStatus,updated_at:new Date().toISOString()}).eq("id",selected.id);const next={...selected,status:nextStatus};setSelected(next);await openTicket(next);await load()}
 const visible=tickets.filter(t=>filter==="all"||filter==="open"&&["open","in_progress","waiting_user"].includes(t.status)||filter==="urgent"&&t.priority==="urgent"||filter==="resolved"&&["resolved","closed"].includes(t.status));
 const staffProfiles=profiles.filter(p=>staffIds.includes(p.id));
 if(loading)return <div className="ma-loader"><BrandIcon size={120}/><strong>Loading Support Console</strong></div>;
 if(!user||!allowed)return <div className="admin-auth-cover"><div className="admin-auth-card"><BrandIcon size={80}/><h1>Restricted</h1><p>Admin, Moderator or Support Team access is required.</p><Link className="admin-primary" href="/admin">Admin Login</Link></div></div>;
 return <div className="support-admin"><header className="support-admin-head"><div><Link href="/admin"><ArrowLeft size={15}/>Back to Admin</Link><h1>Support Ticket Management</h1><p>Central queue for general support, contests, events, businesses, payments and technical issues.</p></div><button onClick={load}>Refresh</button></header>
 <div className="support-admin-stats"><article><LifeBuoy/><span>Open</span><strong>{stats.open}</strong></article><article><ShieldAlert/><span>Urgent</span><strong>{stats.urgent}</strong></article><article><CheckCircle2/><span>Resolved</span><strong>{stats.resolved}</strong></article><article><MessageSquareText/><span>Total</span><strong>{stats.total}</strong></article></div>
 <div className="support-admin-body"><aside><div className="support-admin-filters">{["open","urgent","resolved","all"].map(x=><button className={filter===x?"active":""} key={x} onClick={()=>setFilter(x)}>{x}</button>)}</div><div className="support-admin-list">{visible.map(t=><button key={t.id} className={selected?.id===t.id?"active":""} onClick={()=>openTicket(t)}><div><strong>{t.subject}</strong><span>{t.ticket_number} • {t.category}</span></div><em className={`priority ${t.priority}`}>{t.priority}</em><small>{t.status.replaceAll("_"," ")}</small></button>)}{!visible.length&&<div className="empty-mini">No tickets in this queue.</div>}</div></aside>
 <main>{selected?<><section className="support-admin-ticket-head"><div><span>{selected.ticket_number}</span><h2>{selected.subject}</h2><p>{selected.requester_name||"User"} • {selected.requester_email||selected.requester_phone||"No contact"}</p></div><div className="support-admin-controls"><select value={selected.status} onChange={e=>patch({status:e.target.value,closed_at:e.target.value==="closed"?new Date().toISOString():null})}><option value="open">Open</option><option value="in_progress">In progress</option><option value="waiting_user">Waiting for user</option><option value="resolved">Resolved</option><option value="closed">Closed</option></select><select value={selected.priority} onChange={e=>patch({priority:e.target.value})}><option value="low">Low</option><option value="normal">Normal</option><option value="high">High</option><option value="urgent">Urgent</option></select><select value={selected.assigned_to||""} onChange={e=>patch({assigned_to:e.target.value||null})}><option value="">Unassigned</option>{staffProfiles.map(p=><option key={p.id} value={p.id}>{p.full_name||p.email||p.id}</option>)}</select></div></section>
 <section className="support-admin-context"><div><strong>Category</strong><span>{selected.category}</span></div><div><strong>Related record</strong><span>{selected.related_type||"General"}{selected.related_id?` • ${selected.related_id}`:""}</span></div><div><strong>Created</strong><span>{new Date(selected.created_at).toLocaleString("en-IN")}</span></div></section>
 <section className="support-admin-thread">{messages.map(m=><article className={m.is_internal?"internal":m.sender_role==="user"?"user":"staff"} key={m.id}><div><strong>{m.is_internal?"Internal Note":m.sender_role==="user"?"Customer":"Support Team"}</strong><span>{new Date(m.created_at).toLocaleString("en-IN")}</span></div><p>{m.message}</p></article>)}</section>
 <section className="support-admin-compose"><div><h3>Reply to customer</h3><textarea rows={4} value={reply} onChange={e=>setReply(e.target.value)} placeholder="Write a customer-visible reply…"/><button onClick={()=>send(false)}><Send size={15}/>Send Reply</button></div><div className="internal-note"><h3>Internal note</h3><textarea rows={4} value={internal} onChange={e=>setInternal(e.target.value)} placeholder="Visible only to staff…"/><button onClick={()=>send(true)}>Add Internal Note</button></div></section></>:<div className="support-admin-empty"><LifeBuoy/><h2>Select a ticket</h2><p>Choose a ticket to view its context, assign staff, update priority/status and reply.</p></div>}</main></div>{notice&&<div className="ma-toast">{notice}</div>}</div>;
}
