"use client";
import Link from "next/link";
import {useEffect,useMemo,useState} from "react";
import {supabase} from "@/lib/supabase";
import {BadgeIndianRupee,BriefcaseBusiness,CalendarDays,ChevronLeft,ChevronRight,CircleCheck,Filter,FolderKanban,Image as ImageIcon,LayoutGrid,ListFilter,Package,Plus,Search,Settings2,Tag,Trophy,UsersRound,X} from "lucide-react";
import "./module-manager.css";

type Cfg={title:string;singular:string;table:string;kind:"contest"|"category"|"event"|"package"|"business"|"plan"|"campaign"|"content";description:string;search:string[];fields:{key:string;label:string;type?:"text"|"textarea"|"number"|"boolean"|"select";options?:string[]}[]};
const configs:Record<string,Cfg>={
 contests:{title:"Contests",singular:"Contest",table:"contests",kind:"contest",description:"Run campaigns, publishing status, submissions and search presentation from one workspace.",search:["title","slug","subtitle"],fields:[{key:"title",label:"Contest title"},{key:"slug",label:"URL slug"},{key:"subtitle",label:"Subtitle"},{key:"description",label:"Description",type:"textarea"},{key:"participation_fee",label:"Entry fee",type:"number"},{key:"first_prize",label:"First prize",type:"number"},{key:"submission_close_at",label:"Submission closes"},{key:"is_featured",label:"Featured",type:"boolean"},{key:"is_active",label:"Published",type:"boolean"}]},
 "contest-categories":{title:"Contest Categories",singular:"Contest Category",table:"contest_categories",kind:"category",description:"Organise contest discovery with visual categories, rules and publishing order.",search:["name","slug"],fields:[{key:"name",label:"Name"},{key:"slug",label:"Slug"},{key:"description",label:"Description",type:"textarea"},{key:"icon",label:"Icon"},{key:"color",label:"Accent colour"},{key:"sort_order",label:"Sort order",type:"number"},{key:"is_active",label:"Active",type:"boolean"}]},
 "event-categories":{title:"Event Services",singular:"Event Service",table:"event_categories",kind:"event",description:"Manage event products as services with pricing, publishing state and presentation.",search:["name","slug","description"],fields:[{key:"name",label:"Service name"},{key:"slug",label:"Slug"},{key:"description",label:"Description",type:"textarea"},{key:"base_price",label:"Base price",type:"number"},{key:"sort_order",label:"Sort order",type:"number"},{key:"is_active",label:"Active",type:"boolean"}]},
 "publishing-packages":{title:"Publishing Packages",singular:"Publishing Package",table:"event_packages",kind:"package",description:"Package event publishing benefits and pricing into clear offers.",search:["name","description"],fields:[{key:"name",label:"Package name"},{key:"description",label:"Description",type:"textarea"},{key:"price_modifier",label:"Price",type:"number"},{key:"badge",label:"Badge"},{key:"sort_order",label:"Sort order",type:"number"},{key:"is_active",label:"Active",type:"boolean"}]},
 businesses:{title:"Business Directory",singular:"Business",table:"businesses",kind:"business",description:"Review, publish and maintain complete directory profiles with clearer operational status.",search:["name","city","state","contact_person","email"],fields:[{key:"name",label:"Business name"},{key:"contact_person",label:"Contact person"},{key:"description",label:"Description",type:"textarea"},{key:"city",label:"City"},{key:"state",label:"State"},{key:"phone",label:"Phone"},{key:"email",label:"Email"},{key:"status",label:"Status",type:"select",options:["pending","approved","rejected"]},{key:"is_featured",label:"Featured",type:"boolean"}]},
 "business-categories":{title:"Business Categories",singular:"Business Category",table:"business_categories",kind:"category",description:"Shape directory navigation, category identity and listing rules.",search:["name","slug"],fields:[{key:"name",label:"Name"},{key:"slug",label:"Slug"},{key:"description",label:"Description",type:"textarea"},{key:"icon",label:"Icon"},{key:"sort_order",label:"Sort order",type:"number"},{key:"is_active",label:"Active",type:"boolean"}]},
 "business-plans":{title:"Business Plans",singular:"Business Plan",table:"business_plans",kind:"plan",description:"Control subscriptions, pricing, limits and promotional benefits.",search:["name","description"],fields:[{key:"name",label:"Plan name"},{key:"description",label:"Description",type:"textarea"},{key:"registration_fee",label:"Registration fee",type:"number"},{key:"monthly_price",label:"Monthly price",type:"number"},{key:"annual_price",label:"Annual price",type:"number"},{key:"trial_days",label:"Trial days",type:"number"},{key:"is_active",label:"Active",type:"boolean"}]},
 campaigns:{title:"Campaign Studio",singular:"Campaign",table:"campaigns",kind:"campaign",description:"Build and schedule homepage campaigns with a visual-first workflow.",search:["title","subtitle","campaign_type"],fields:[{key:"title",label:"Title"},{key:"subtitle",label:"Subtitle"},{key:"description",label:"Description",type:"textarea"},{key:"campaign_type",label:"Campaign type"},{key:"cta_label",label:"CTA label"},{key:"start_at",label:"Starts"},{key:"end_at",label:"Ends"},{key:"is_active",label:"Active",type:"boolean"}]},
 content:{title:"CMS Content",singular:"Content Item",table:"cms_content",kind:"content",description:"Manage reusable frontend content, promotional blocks and banners.",search:["title","key","body"],fields:[{key:"title",label:"Title"},{key:"key",label:"Content key"},{key:"body",label:"Body",type:"textarea"},{key:"link_url",label:"Link URL"},{key:"is_active",label:"Active",type:"boolean"}]}
};
const PAGE=8;
const money=(n:any)=>`₹${Number(n||0).toLocaleString("en-IN")}`;
const nice=(v:any)=>String(v||"").replaceAll("_"," ").replace(/\b\w/g,c=>c.toUpperCase());
function icon(kind:string){return kind==="contest"?<Trophy/>:kind==="event"?<CalendarDays/>:kind==="business"?<BriefcaseBusiness/>:kind==="package"||kind==="plan"?<Package/>:kind==="campaign"?<ImageIcon/>:kind==="category"?<Tag/>:<FolderKanban/>}
export default function ModuleManager({module}:{module:string}){
 const cfg=configs[module];const [rows,setRows]=useState<any[]>([]),[loading,setLoading]=useState(true),[q,setQ]=useState(""),[status,setStatus]=useState("all"),[page,setPage]=useState(1),[editor,setEditor]=useState<any|null>(null),[form,setForm]=useState<any>({}),[saving,setSaving]=useState(false),[message,setMessage]=useState("");
 async function load(){if(!cfg)return;setLoading(true);const {data,error}=await supabase.from(cfg.table).select("*").order("created_at",{ascending:false});setRows(data||[]);if(error)setMessage(error.message);setLoading(false)}
 useEffect(()=>{load()},[module]);
 const filtered=useMemo(()=>rows.filter(r=>{const hay=cfg.search.map(k=>r[k]).join(" ").toLowerCase();if(q&&!hay.includes(q.toLowerCase()))return false;if(status!=="all"){if(cfg.kind==="business"&&r.status!==status)return false;if(cfg.kind!=="business"&&status==="active"&&r.is_active!==true)return false;if(cfg.kind!=="business"&&status==="inactive"&&r.is_active!==false)return false;}return true}),[rows,q,status,module]);
 useEffect(()=>setPage(1),[q,status,module]);
 const pages=Math.max(1,Math.ceil(filtered.length/PAGE)),visible=filtered.slice((page-1)*PAGE,page*PAGE);
 const active=cfg.kind==="business"?rows.filter(r=>r.status==="approved").length:rows.filter(r=>r.is_active!==false).length;
 const pending=cfg.kind==="business"?rows.filter(r=>r.status==="pending").length:rows.filter(r=>r.is_active===false).length;
 function open(row:any|null){const f:any={};cfg.fields.forEach(x=>f[x.key]=row?.[x.key]??(x.type==="boolean"?false:""));setForm(f);setEditor(row||{})}
 async function save(){setSaving(true);const payload:any={};cfg.fields.forEach(x=>payload[x.key]=x.type==="number"?(form[x.key]===""?null:Number(form[x.key])):x.type==="boolean"?!!form[x.key]:form[x.key]||null);let error;if(editor?.id)({error}=await supabase.from(cfg.table).update(payload).eq("id",editor.id));else ({error}=await supabase.from(cfg.table).insert(payload));setSaving(false);if(error){setMessage(error.message);return}setEditor(null);load()}
 async function del(r:any){if(!confirm(`Delete ${cfg.singular.toLowerCase()} “${r.name||r.title||r.key}”?`))return;const {error}=await supabase.from(cfg.table).delete().eq("id",r.id);if(error)setMessage(error.message);else load()}
 if(!cfg)return <div className="mm-shell"><h1>Unknown module</h1></div>;
 const statusOptions=cfg.kind==="business"?["all","pending","approved","rejected"]:["all","active","inactive"];
 return <div className={`mm-shell mm-${cfg.kind}`}>
  <section className="mm-hero"><div className="mm-hero-icon">{icon(cfg.kind)}</div><div className="mm-hero-copy"><span>{cfg.kind==="category"?"TAXONOMY":cfg.kind==="package"||cfg.kind==="plan"?"PRICING & OFFERS":cfg.kind==="business"?"DIRECTORY OPERATIONS":cfg.kind==="contest"?"CONTEST OPERATIONS":cfg.kind==="event"?"EVENT CATALOG":"CONTENT OPERATIONS"}</span><h1>{cfg.title}</h1><p>{cfg.description}</p></div><button className="mm-primary" onClick={()=>open(null)}><Plus size={18}/> Add {cfg.singular}</button></section>
  <section className="mm-stats"><div><small>Total</small><strong>{rows.length}</strong><span>records</span></div><div><small>{cfg.kind==="business"?"Published":"Active"}</small><strong>{active}</strong><span>visible/available</span></div><div><small>{cfg.kind==="business"?"Needs review":"Inactive"}</small><strong>{pending}</strong><span>needs attention</span></div><div><small>Showing</small><strong>{filtered.length}</strong><span>after filters</span></div></section>
  <section className="mm-toolbar"><label><Search size={18}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder={`Search ${cfg.title.toLowerCase()}…`}/></label><div className="mm-filter"><ListFilter size={16}/>{statusOptions.map(s=><button key={s} className={status===s?"active":""} onClick={()=>setStatus(s)}>{nice(s)}</button>)}</div></section>
  {message&&<div className="mm-message">{message}<button onClick={()=>setMessage("")}><X size={15}/></button></div>}
  <section className={`mm-list mm-list-${cfg.kind}`}>{loading?<div className="mm-empty">Loading {cfg.title.toLowerCase()}…</div>:visible.length?visible.map(r=><Card key={r.id} cfg={cfg} row={r} onEdit={()=>open(r)} onDelete={()=>del(r)}/>):<div className="mm-empty"><Filter size={26}/><strong>No matching records</strong><span>Clear your search or change the filter.</span></div>}</section>
  <footer className="mm-pagination"><span>{filtered.length?`${(page-1)*PAGE+1}–${Math.min(page*PAGE,filtered.length)} of ${filtered.length}`:"0 records"}</span><div><button disabled={page<=1} onClick={()=>setPage(p=>p-1)}><ChevronLeft size={17}/></button>{Array.from({length:pages},(_,i)=>i+1).slice(Math.max(0,page-3),Math.max(5,page+2)).map(p=><button className={page===p?"active":""} onClick={()=>setPage(p)} key={p}>{p}</button>)}<button disabled={page>=pages} onClick={()=>setPage(p=>p+1)}><ChevronRight size={17}/></button></div></footer>
  {editor!==null&&<div className="mm-modal-wrap" onMouseDown={e=>{if(e.target===e.currentTarget)setEditor(null)}}><div className="mm-modal"><header><div><span>{editor.id?"EDIT":"CREATE"}</span><h2>{editor.id?editor.name||editor.title||cfg.singular:`New ${cfg.singular}`}</h2></div><button onClick={()=>setEditor(null)}><X/></button></header><div className="mm-form">{cfg.fields.map(f=><label key={f.key} className={f.type==="textarea"?"wide":""}><span>{f.label}</span>{f.type==="textarea"?<textarea value={form[f.key]||""} onChange={e=>setForm({...form,[f.key]:e.target.value})}/>:f.type==="boolean"?<button type="button" className={form[f.key]?"mm-toggle on":"mm-toggle"} onClick={()=>setForm({...form,[f.key]:!form[f.key]})}><i/>{form[f.key]?"Enabled":"Disabled"}</button>:f.type==="select"?<select value={form[f.key]||""} onChange={e=>setForm({...form,[f.key]:e.target.value})}>{f.options?.map(o=><option value={o} key={o}>{nice(o)}</option>)}</select>:<input type={f.type==="number"?"number":"text"} value={form[f.key]??""} onChange={e=>setForm({...form,[f.key]:e.target.value})}/>}</label>)}</div><footer><button className="mm-secondary" onClick={()=>setEditor(null)}>Cancel</button><button className="mm-primary" disabled={saving} onClick={save}>{saving?"Saving…":"Save changes"}</button></footer></div></div>}
 </div>
}
function Card({cfg,row,onEdit,onDelete}:{cfg:Cfg,row:any,onEdit:()=>void,onDelete:()=>void}){
 if(cfg.kind==="contest")return <article className="mm-contest-card"><div className="mm-cover" style={row.banner_url?{backgroundImage:`linear-gradient(90deg,rgba(35,12,27,.82),rgba(35,12,27,.15)),url(${row.banner_url})`}:{}}><span>{row.is_featured?"Featured contest":"Contest"}</span><h3>{row.title}</h3><p>{row.subtitle||row.slug}</p></div><div className="mm-card-body"><div className="mm-facts"><span><small>Status</small><b className={row.is_active?"ok":"muted"}>{row.is_active?"Published":"Draft"}</b></span><span><small>Entry</small><b>{money(row.participation_fee)}</b></span><span><small>Prize</small><b>{money(row.first_prize)}</b></span></div><Actions cfg={cfg} row={row} onEdit={onEdit} onDelete={onDelete}/></div></article>;
 if(cfg.kind==="business")return <article className="mm-business-row"><div className="mm-business-avatar">{row.logo_url?<img src={row.logo_url} alt=""/>:<BriefcaseBusiness/>}</div><div className="mm-business-main"><h3>{row.name}</h3><p>{[row.city,row.state].filter(Boolean).join(", ")||"Location not set"}</p></div><span className={`mm-status ${row.status}`}>{nice(row.status)}</span><div className="mm-business-contact"><small>{row.contact_person||"No contact"}</small><span>{row.email||row.phone||"—"}</span></div><Actions cfg={cfg} row={row} onEdit={onEdit} onDelete={onDelete}/></article>;
 if(cfg.kind==="package"||cfg.kind==="plan")return <article className="mm-price-card"><span className="mm-price-badge">{row.badge||"Plan"}</span><h3>{row.name}</h3><div className="mm-price">{money(row.price_modifier??row.monthly_price)}<small>{cfg.kind==="plan"?"/ month":""}</small></div><p>{row.description||"No description added yet."}</p><div className="mm-plan-state"><CircleCheck size={15}/>{row.is_active!==false?"Available":"Inactive"}</div><Actions cfg={cfg} row={row} onEdit={onEdit} onDelete={onDelete}/></article>;
 if(cfg.kind==="event")return <article className="mm-event-card"><div className="mm-event-art">{row.image_url?<img src={row.image_url} alt=""/>:<CalendarDays/>}</div><div><span>EVENT SERVICE</span><h3>{row.name}</h3><p>{row.description||row.slug}</p></div><div className="mm-event-price"><small>From</small><strong>{money(row.base_price)}</strong><span className={row.is_active?"ok":"muted"}>{row.is_active?"Active":"Hidden"}</span></div><Actions cfg={cfg} row={row} onEdit={onEdit} onDelete={onDelete}/></article>;
 if(cfg.kind==="category")return <article className="mm-category-card"><div className="mm-category-icon"><Tag/></div><span className={row.is_active!==false?"ok":"muted"}>{row.is_active!==false?"Active":"Hidden"}</span><h3>{row.name}</h3><p>/{row.slug}</p><small>{row.description||"Category presentation and rules"}</small><Actions cfg={cfg} row={row} onEdit={onEdit} onDelete={onDelete}/></article>;
 return <article className="mm-default-card"><div><h3>{row.title||row.name||row.key}</h3><p>{row.subtitle||row.description||row.key}</p></div><Actions cfg={cfg} row={row} onEdit={onEdit} onDelete={onDelete}/></article>
}
function Actions({cfg,row,onEdit,onDelete}:{cfg:Cfg,row:any,onEdit:()=>void,onDelete:()=>void}){return <div className="mm-actions">{["contest","event","business"].includes(cfg.kind)&&<Link href={`/admin/${cfg.kind==="event"?"events":cfg.kind==="business"?"businesses":"contests"}/${row.id}/seo`}>SEO</Link>}<button onClick={onEdit}><Settings2 size={15}/>Manage</button><button className="danger" onClick={onDelete}>Delete</button></div>}
