"use client";
import { useCallback,useEffect,useState } from "react";
import { ArrowLeft,Pencil,RefreshCw,Search,ShieldCheck,Trash2,X } from "lucide-react";
import { supabase } from "@/lib/supabase";
import { BrandIcon } from "@/components/BrandLogo";
const TABLES=["contest_submissions","event_submissions","businesses","subscriptions","payments","support_tickets","public_videos","winners","notifications","payout_details"];
export default function AdvancedDataControl(){const [user,setUser]=useState<any>(null),[ok,setOk]=useState(false),[checking,setChecking]=useState(true),[table,setTable]=useState(TABLES[0]),[rows,setRows]=useState<any[]>([]),[query,setQuery]=useState(""),[edit,setEdit]=useState<any>(null),[json,setJson]=useState("");
 const load=useCallback(async(u:any,t=table)=>{if(!u){setChecking(false);return}const {data:r}=await supabase.from("user_roles").select("role").eq("user_id",u.id).eq("role","admin").maybeSingle();if(!r){setChecking(false);return}setOk(true);const {data}=await supabase.from(t).select("*").limit(250);setRows(data||[]);setChecking(false)},[table]);
 useEffect(()=>{supabase.auth.getUser().then(({data})=>{setUser(data.user);load(data.user)});},[load]);
 async function choose(t:string){setTable(t);setQuery("");if(user){setChecking(true);await load(user,t)}}
 async function save(){if(!edit)return;let payload:any;try{payload=JSON.parse(json)}catch{return alert("Invalid JSON")};delete payload.id;const {error}=await supabase.from(table).update(payload).eq("id",edit.id);if(error)alert(error.message);setEdit(null);load(user,table)}
 async function del(r:any){if(!confirm(`Permanently delete this record from ${table}?`))return;const {error}=await supabase.from(table).delete().eq("id",r.id||r.user_id);if(error)alert(error.message);load(user,table)}
 if(checking)return <div className="ma-loader"><BrandIcon size={120}/><strong>Loading Advanced Data Control</strong><span><i/></span></div>;if(!ok)return <div className="admin-auth-cover"><div className="admin-auth-card"><ShieldCheck/><h1>Admin access required</h1><a href="/admin">Return to admin login</a></div></div>;
 const filtered=rows.filter(r=>!query||JSON.stringify(r).toLowerCase().includes(query.toLowerCase()));return <div className="master-admin" style={{display:"block"}}><main className="ma-main" style={{marginLeft:0,width:"100%"}}><header><div style={{display:"flex",alignItems:"center",gap:10}}><a href="/admin" className="ma-menu" style={{display:"inline-flex"}}><ArrowLeft/></a><div><h1>Advanced Data Control</h1><p>Direct edit/delete access for operational records. Use carefully.</p></div></div><button onClick={()=>load(user,table)}><RefreshCw size={14}/> Refresh</button></header><div className="ma-content"><div className="ma-section-head"><div><h2>Operational Tables</h2><p>This is the administrator fallback for records without a specialized visual editor.</p></div></div><div className="ma-actions" style={{justifyContent:"flex-start",marginBottom:14}}>{TABLES.map(t=><button className={table===t?"primary":""} onClick={()=>choose(t)} key={t}>{t.replaceAll("_"," ")}</button>)}</div><div className="ma-search"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search record JSON…"/></div><div className="ma-resource-list">{filtered.map((r:any,i)=><article key={r.id||r.user_id||i}><div><strong>{r.title||r.name||r.reference_code||r.email||r.id||r.user_id}</strong><span>{r.status||r.purpose||table}</span></div><div className="ma-actions"><button onClick={()=>{setEdit(r);setJson(JSON.stringify(r,null,2))}}><Pencil/>Edit JSON</button><button className="danger" onClick={()=>del(r)}><Trash2/>Delete</button></div></article>)}</div></div></main>{edit&&<div className="ma-modal-bg"><div className="ma-modal"><header><div><h2>Edit {table} record</h2><p>Update any editable column using JSON.</p></div><button onClick={()=>setEdit(null)}><X/></button></header><div style={{padding:18}}><textarea style={{width:"100%",minHeight:"60vh",fontFamily:"monospace",fontSize:12,padding:12,border:"1px solid #d0d5dd",borderRadius:8}} value={json} onChange={e=>setJson(e.target.value)}/></div><footer><button onClick={()=>setEdit(null)}>Cancel</button><button className="primary" onClick={save}>Save Record</button></footer></div></div>}</div>}
